### ISSUE TITLE
Allow for overriding the Scaladoc URL by project maintainers

### ISSUE THREAD

**Issue by alexandru** [scalacenter/scaladex#100]
My project is split in multiple sub-projects and the Scaladoc that's going to get generated by https://www.javadoc.io is going to be poor. What I do is to prepare the Scaladoc using [sbt-unidoc](https://github.com/sbt/sbt-unidoc) and I upload those docs to the project's website on every release.

Compare whatever output of https://javadoc.io for project [Monix](https://index.scala-lang.org/monixio/monix) with this one: https://monix.io/api/2.0-RC7/

I'd like the ability to redirect users to the project's official Scaladoc URL. Preferably with a variable template for that version. Eg... `https://monix.io/api/{{version}}/` (though I guess we could always redirect to some `current` version so this isn't necessarily required).

**Comment by MasseGuillaume** [comment]
I studied some projects from the index and I came up with this pseudo dsl:

given "io.monix" %% "monix-reactive" % "2.0-RC8"

```
[version] => "2.0-RC8"
[major] => "2"
[minor] => "0"
[name] => "monix-reactive"
```

* scaladoc: "https://monix.io/api/[version]/#package"
* documentation =
  * user: https://monix.io/docs/[major]x/
  * ...

becomes:

* scaladoc: "https://monix.io/api/2.0-RC8/#package"),
* documentation =
  * user: https://monix.io/docs/2x/
  * ...

**Comment by MasseGuillaume** [comment]
@alexandru 
![demo](https://cloud.githubusercontent.com/assets/921490/17087634/ee2a9a5e-51dc-11e6-8816-a150e17262fe.gif)

**Comment by MasseGuillaume** [comment]
![2016-07-24-210017_2446x1920_scrot](https://cloud.githubusercontent.com/assets/921490/17087934/d6b54b4e-51e1-11e6-91d3-2e90446b03da.png)

**Comment by alexandru** [comment]
Thanks, looking good.

**Comment by MasseGuillaume** [comment]
* [ ] add url label

**Comment by MasseGuillaume** [comment]
@alexandru the edit feature is now live

can you update https://index.scala-lang.org/monixio/monix ?

**Comment by heathermiller** [comment]
(The color-changing part of the edit feature is coming in a later pass, but the rest is there!)

**Comment by MasseGuillaume** [comment]
Regarding Monifu there is a pending issue for moved repository

https://github.com/scalacenter/scaladex/issues/95

**Comment by alexandru** [comment]
Thanks folks, will update when I get back this Sunday, currently on vacation :-)

**Comment by alexandru** [comment]
Just wanted to report that I've edited the documentation link, it seems to be working fine.

I also submitted a claim request to scaladex-data for the Monifu repository, thanks @MasseGuillaume for the notice.
