### ISSUE TITLE
[Bug] Lot's of 500 from Maven Central when there is a surge of request

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#1010]
### Current behavior

When Maven Centrals as a surge of published Scala artifacts, it sends a burst of traffic to Scaladex and the server cannot handle the high load resulting in a lot of 500s.

### Expected Behavior

Scaladex should be able to handle a burst of traffic on it's `PUT /publish` endpoint.

### Extra comments

https://github.com/scalacenter/scaladex/blob/main/modules/server/src/main/scala/scaladex/server/route/api/PublishApi.scala

A common solution for this problem is to accept all incoming request with a `201 Created` Status Code and add it to a persistent message queue (for example RabbitMQ).

**Comment by scherzhaft** [comment]
The Central job that does this, is single threaded, with most workload completing under 10 minutes, if thats helpful.

**Comment by adpi2** [comment]
Thanks for reporting this error. It was caused by an bug in the authentication of central-ossrh user.
