### ISSUE TITLE
Ability to add projects with no published artifacts to Maven Central

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#1032]
### Motivation

Currently only the projects that publishes to Maven Central are going to be indexed into Scaladex. This is okay because Maven Central is predominant in the Scala ecosystem.

However we expect some library authors to experiment with other package repositories like [Github Packages](https://github.com/features/packages), or maybe they don't publish any artifacts at all.

Before we integrate Scaladex with other package repositories, it would be good to be able to manually insert a Github repository, without any known artifacts.

### Identified Obstacles

Scaladex should be able to load the project pages of a project with no artifacts.

### Implementation Guideline

- [x] #1077 In the `AdminService` add a method that takes a `Project.Reference` and that start a task that insert it into the database. As an example of what a task is you can see the `AdminService#runMissingArtifactsTask`.
- [ ]  In the `AdminPages` add a POST endpoint that expects a `Project.Reference` and that call the `AdminService`.
- [ ]  Make sure that we can load the project page of a project with no artifact. Currently it will fail in `ProjectPages` because it expects every project to have a latest version. So `WebDatabase#getLatestVersion` should return an option. Maybe other methods should be adapted in the same way.
- [ ]  Optionnaly, in the `AdminService` method, we should check that the project is valid by calling the `GithubClient.getProjectInfo` on it: the response should be ok, and the percentage of Scala code should be greater than 0.

### Expectations

An admin can insert a project from the admin page: https://index.scala-lang.org/admin. (The admin page is only accessible to Scaladex admins but anyone can try it locally on https://localhost:8080/admin)

**Comment by adpi2** [comment]
Hello @mfirry and thanks for jumping here!

The task itself must do three things:
1. Check that the project that we want to add exists in Github and that it is a Scala project. To do that we can use `githubClient.getProjectInformation(ref)` and check that `githubInfo.scalaPercentage` is greater than 0.
2.  Then store the project in the database with: `database.insertProject(project)`
3. Sync the search engine with: `searhcSynchronizer.syncProject(reference)`


So it could look like this:
```scala
def runInsertProject(ref: Project.Reference): Unit = {
  val input  = Seq(???)
  val task =  TaskRunner.run(Task.addNewProject, user.info.login, input) { () =>
     githubClient.getProjectInformation(ref).flatMap {
       case GithubResponse.Ok((_, info)) =>
          if (info.scalaPercentage <= 0) throw new Exception("Failed because ???")
          else {
            val project = Project(...)
            database.insertProject(project)
              .flatMap(_ => searchSynchronizer.sync(projectRef))
              .map(_ => "success")
          }
      case _ => throw new Exception("Failed because ???")
     }
  }
  tasks = tasks :+ task
}
```

The input is the thing that we show to the user on the admin page. So it could be something like `Seq("Organization" ->  ref.organization, "Repository" -> ref.repository)`

**Comment by mfirry** [comment]
Thanks @adpi2. I can work on a draft PR if that's ok.
Or rather maybe I can _show_ somehow what I have in mind and then you (or anybody who can) fill my gaps?
The point is I want to be able to fit in the overall structure/style of the code here.
