### ISSUE TITLE
[Bug] Missing bullets in list items

### ISSUE THREAD

**Issue by plokhotnyuk** [scalacenter/scaladex#1043]
In the readme of a project, the bullets are not displayed.

See for instance: https://index.scala-lang.org/plokhotnyuk/jsoniter-scala

### Current behavior

![image](https://user-images.githubusercontent.com/890289/176630864-ebc130dd-ae5f-412d-b39a-9c92829efc43.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/890289/176630766-bd2e4e14-1d68-42bd-a952-e54a6c15645b.png)

**Comment by adpi2** [comment]
Thanks for opening this issue.
