### ISSUE TITLE
Scala 3.x is not shown for module with Scala Native / Scala 3.

### ISSUE THREAD

**Issue by carlosedp** [scalacenter/scaladex#1076]
Scaladex does not show that the module have Scala 3.x support on Scala Native:

![image](https://user-images.githubusercontent.com/20382/191564391-ba29da4e-cfac-40b1-b793-43bcc1a95a71.png)

As seen here, the artifacts exists:

![image](https://user-images.githubusercontent.com/20382/191564528-cd1c334b-9089-44aa-b8e5-10df3bc76d48.png)

**Comment by adpi2** [comment]
Thanks for opening this issue!

In the logs I can see that we received a publish request for all artifacts but not for `riscvassembler_native0.4_3`. So it looks like  Sonatype did not push the artifact to us.

Hopefully we have a background job that will find the missing artifact and fetch it. But this job is slow, it will take a few more hours. I will check again tomorrow to see if the artifact is still missing.

**Comment by carlosedp** [comment]
Awesome, I've noticed this first on mainargs.. It was published but didn't show up:

https://repo1.maven.org/maven2/com/lihaoyi/mainargs_native0.4_3/0.3.0/

![image](https://user-images.githubusercontent.com/20382/191750751-bdf18c3f-1bc5-4262-b734-bb770c6f007e.png)

**Comment by adpi2** [comment]
Ok so this is not a random failure and I should report it to Sonatype.

**Comment by carlosedp** [comment]
Apparently this is fixed.
