### ISSUE TITLE
Display date & time of last scan

### ISSUE THREAD

**Issue by peter-empen** [scalacenter/scaladex#108]
To my use case:
My library is one of those not showing up at all on Scaladex. After examining my pom parameters I polished them up to obey to the assumed inclusion rules. On June 20, I published a release based on the new pom that, I'am pretty sure, suffices for inclusion. Ever since the newest library displayed is from 18/06/2016 and I'm stuck.

It would be great to see on the home page when the last scan took place. Then I could reason about whether I need to further wait for a scan or I need to take further action to ensure the library is accepted.

Even better, you could display the date & time of the next expected scan in addition.

**Comment by Scyks** [comment]
Hey, actually there is no nightly build/reindexing. That's why your library is still not updates (mine as well).
As far as i know, tomorrow will be a release and reindexing.

A nightly build/reindexing is also on the roadmap.  We're working on that.

**Comment by Scyks** [comment]
@peter-empen Which artifact is it? Can you provide a link to maven? Then we can try that in development environment. Would be helpful.

Thank you :)

**Comment by peter-empen** [comment]
Hi Ronald, the artifact in question with the actualized pom:
http://search.maven.org/#artifactdetails%7Corg.scala-graph%7Cgraph-core_2.11%7C1.11.1
and the old pom:
http://search.maven.org/#artifactdetails%7Ccom.assembla.scala-incubator%7Cgraph-core_2.11%7C1.11.0
Thanks, too.

**Comment by Scyks** [comment]
@peter-empen I updated the claims.js file in scalacenter/scaladex-data. Can you please check if i did that right? https://github.com/scalacenter/scaladex-data/pull/2/commits/e69267a6c5bb549396d53b2ab5918b6afea12fe9

After new reindexing, both packages should be available on http://index.scala-lang.org.

Best
Ronald

**Comment by peter-empen** [comment]
Thank you, Ronald,
that looks all right. You may just remove graph-test on line 176 since this module has been included in _graph-core_ sometime in 2015.
In near future all artifacts will be released under the groupId _org.scala-graph_ making _com.assembla.scala-incubator_ obsolate. I'd get back to you once that has happened.

**Comment by MasseGuillaume** [comment]
@peter-empen we still next to keep track of the old  stuff. We have a ticket to mark artifact as deprecated with an alternative artifact

**Comment by peter-empen** [comment]
Hi Ronald, hi Masse,
Scalasdex is now reindexed but your entry in claims.js did not work out. I wonder what the reason is for scala-graph still not showing up?

**Comment by Scyks** [comment]
@peter-empen I investigated this a bit further and as @heathermiller wrote, the claimed repos where not indexed. I fixed that locally, reindexed everything and now it seems to work. I guess you need to wait for the next deployment. I'm sorry for that.

<img width="1217" alt="scala-graph" src="https://cloud.githubusercontent.com/assets/875242/16540056/830ad456-4056-11e6-8d49-a60d9569bf8b.png">
