### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by cvogt** [scalacenter/scaladex#110]
rapture appears in the search results for the testing keyword as this: https://index.scala-lang.org/propensive/rapture-core-test

the readme seems to be all of rapture though and clicking at in the list of dependencies leads to an empty page

**Comment by MasseGuillaume** [comment]
okay two things

> the readme seems to be all of rapture though

1. I know explaining a UI is silly and it's like telling a bad joke. But here it is anyway:
When you are on an artifact page (https://index.scala-lang.org/propensive/rapture-core-test) you see everything related to the project on the left (Website, keywords, Github Readme). On the right it's everything related to a release (install string, dependencies, etc). This relates to #94. You think we should not show README on scaladex, fair point.

> clicking at in the list of dependencies leads to an empty page

2. look like we are talking about those links:
* https://index.scala-lang.org/propensive/rapture-test/2.0.0-M6 (empty page)
* https://index.scala-lang.org/propensive/rapture-core-scalaz/2.0.0-M6 (empty release section)

Look like a combination of bugs (#48 and something else)
