### ISSUE TITLE
Outdated description on scaladex page.

### ISSUE THREAD

**Issue by SuperIzya** [scalacenter/scaladex#1100]
Scaladex page for [dbzio](https://index.scala-lang.org/riskidentdms/dbzio) was created when the git-repo had a description with type. Now git description is fix, while the scaladex page still contains old description with type ("Monadic bridge between DBIO & **DBZIO**" instead of "Monadic bridge between DBIO & ZIO")

**Comment by adpi2** [comment]
Thanks for opening this issue.

It seems that the Scaladex server restarts regularly and, as a consequence, the background job that updates all the Github info gets interrupted.

**Comment by adpi2** [comment]
Looks better now.

We still have some `java.net.UnknownHostException: api.github.com` errors sometimes that could be caught and ignored.

Also please note that updating the Github info can take up to 24 hours.
