### ISSUE TITLE
[Bug] Project not being indexed

### ISSUE THREAD

**Issue by ghostdogpr** [scalacenter/scaladex#1105]
### Current behavior

Our project [Shardcake](https://github.com/devsisters/shardcake) is not indexed by Scaladex.
It is published on Maven and I believe the scm tags are correct (for example https://s01.oss.sonatype.org/content/repositories/releases/com/devsisters/shardcake-core_2.13/2.0.4/shardcake-core_2.13-2.0.4.pom).
I think it may be caused by the fact that the project repository was initially private and was made public *after* the first release. But it's been a couple months and a few releases since and it still does not appear. Any idea why?
Thanks!

### Expected Behavior

Shardcake appears in Scaladex.

### Search terms

shardcake, sharding

**Comment by adpi2** [comment]
Thanks for opening this issue.

> I think it may be caused by the fact that the project repository was initially private and was made public after the first release. But it's been a couple months and a few releases since and it still does not appear. Any idea why?
Thanks!

I think you are correct. Scaladex usually tries to reindex all artifacts from known groupId. But it seems there is no other `com.devsisters` artifacts. So I started manually a job to add all the not-yet-indexed `com.devsisters` artifacts.

**Comment by yoohaemin** [comment]
I'm having the same issue for my project :thinking: 
https://github.com/yoohaemin/decrel
https://central.sonatype.dev/artifact/com.yoohaemin/decrel-core_3/0.1.0-M1

**Comment by sake92** [comment]
Same for https://github.com/sake92/squery and https://github.com/sake92/tupson  
I do have some older projects which were indexed before..

**Comment by adpi2** [comment]
@sake92 It seems that your projects are correctly indexed: https://index.scala-lang.org/sake92/squery and https://index.scala-lang.org/sake92/tupson

Same for you @yoohaemin: https://index.scala-lang.org/yoohaemin/decrel 

Or am I missing something?

**Comment by ghostdogpr** [comment]
Oh, actually shardcake is there too: https://index.scala-lang.org/devsisters/shardcake

But none of them appear in search results.

**Comment by ghostdogpr** [comment]
Looks like they are not fully indexed like the others, for example they don't have description, tags, statistics, link to documentation, etc.

**Comment by adpi2** [comment]
Thanks for your replies, that helps.

It seems the artifacts are indexed, but Scaladex is not able to fetch any project info from Github. So there are potentially two related bugs:
- cannot fetch information from Github
- cannot index project with missing Github information in search

**Comment by adpi2** [comment]
All your projects should now contain all the Github information and be indexed in the search.

**Comment by ghostdogpr** [comment]
Awesome, thank you!
