### ISSUE TITLE
Strategy to determine libraries with "Help wanted"

### ISSUE THREAD

**Issue by raulraja** [scalacenter/scaladex#112]
@MasseGuillaume It turns out that all Github Repos come with built in labels for issues. One of the labels is `help wanted`. We could potentially iterate over the project issues and determine if it's a project wanting help by the presence of these tags in their issue list.

**Comment by Scyks** [comment]
This could be a featured tag (#90, #113) then, that you can search for artifacts with `help wanted`. That's a very cool idea.

**Comment by MasseGuillaume** [comment]
This is a good idea! I'm curious to see how often this is used already.

**Comment by Scyks** [comment]
Regarding the github search it's 782 issues for scala:
https://github.com/search?l=scala&q=label%3A%22help+wanted%22&ref=searchresults&type=Issues&utf8=%E2%9C%93

**Comment by MasseGuillaume** [comment]
* [add `List[Issue]` to the model for the github api](https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/github/GithubModel.scala#L1)
* [add `List[Issue]` to the scaladex model](
https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/misc/GithubInfo.scala#L17)
* [modify the function to convert github api model to scaladex model](https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/github/GithubReader.scala#L24)
* [add a step to download github issues](
https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/github/GithubDownload.scala#L278)
* (convert contributorsWanted from `Boolean` to `Option[Boolean]` where `None` means it was not defined by the user, `Some(x)` it was set by the user)[https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/Project.scala#L39]
* [count `help wanted` issues to update the project](https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/project/ProjectConvert.scala#L139)

https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/project/ProjectConvert.scala#L139

**Comment by MasseGuillaume** [comment]
this is now the scope of @MichaelViveros 's GSOC project.

**Comment by MasseGuillaume** [comment]
This is now live! Check it out.
