### ISSUE TITLE
[Bug] 404 for all CSS

### ISSUE THREAD

**Issue by plokhotnyuk** [scalacenter/scaladex#1134]
### Current behavior

![image](https://user-images.githubusercontent.com/890289/206756783-f56c364e-a73a-4203-84e6-0603a8eda533.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/890289/206756931-6ae5703a-2ef1-43c4-8535-f442bcdc7758.png)

**Comment by plokhotnyuk** [comment]
It works fine now. Probably some infrastructure issue was fixed

**Comment by julienrf** [comment]
Thank you for reporting, indeed there was an issue during the deployment process. This is now fixed, as you have noticed.
