### ISSUE TITLE
Re-add and wire up statistics (UI is there, but GitHub HTTP reqs not)

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#115]
<img width="617" alt="screen shot 2016-06-25 at 11 09 59 am" src="https://cloud.githubusercontent.com/assets/687163/16355873/63de3d66-3ac5-11e6-9e2c-241a4a6cc526.png">

**Comment by Scyks** [comment]
There might be a problem collecting the collaborators for a project. Actually i get a response that i need push access to this repo. Documentation says nothing about this error.
Maybe we should include this in the Interface and manually enable this function:
Docu: https://developer.github.com/v3/repos/collaborators/
Response:
```
{
   "message":"Must have push access to view repository collaborators.",
   "documentation_url":"https://developer.github.com/v3"
}
```
