### ISSUE TITLE
Show Scala versions in descending order

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scaladex#1151]
instead of "2.10 2.11 2.12 2.13 3.x", IMO it should show as "3.x 2.13 2.12 2.11 2.10", on the general design principle of putting the more important things first

(suggested on Discord by @keynmol)

**Comment by sjrd** [comment]
Further, IMO this applies to most categories: sbt 1.x first, Scala.js 1.x first, Scala Native 0.4.x first, etc.

**Comment by keynmol** [comment]
something like this?

<img width="555" alt="image" src="https://user-images.githubusercontent.com/1052965/215550224-e161b2aa-f749-44ce-8c87-d8d845137290.png">

**Comment by keynmol** [comment]
Here's my PR for it: https://github.com/scalacenter/scaladex/pull/1153

I was also thinking of same reordering on the results page: 
![image](https://user-images.githubusercontent.com/1052965/215570979-b974a34e-0d20-429f-9b9a-f7bc6d6355d5.png)

Can do it as part of the same PR, as long as I get a thumbsup on the general approach.

**Comment by SethTisue** [comment]
yes, LGTM
