### ISSUE TITLE
[Bug] The Site is down

### ISSUE THREAD

**Issue by TonioGela** [scalacenter/scaladex#1166]
### Current behavior

`$ curl https://index.scala-lang.org/`

👇

```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### Expected Behavior

The site working as usual

**Comment by adpi2** [comment]
I was redoplying Scaladex at that time and it took me a bit more than usual. Sorry for the inconvenience and thanks for reporting.

**Comment by TonioGela** [comment]
No worries, I probably hit the minute you were deploying. I've been particularly lucky/unlucky :D
