### ISSUE TITLE
Restore autocomplete/dropdown bar

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#122]

**Comment by MasseGuillaume** [comment]
Hey @jvican!

This is how you get started:
https://github.com/scalacenter/scaladex#how-to-run-scaladex

You will need to install sass
https://github.com/scalacenter/scaladex#requirements

To simplify the build I removed scalajs and the only feature we had using it (dropdown in search). It would like to keep it simple and use plain javascript for the client side.

This was the scalajs code:
https://github.com/scalacenter/scaladex/commit/72fa081899dfee15a902fa66230ad23dc2d46643#diff-f7a3ec9b440b60b4b2f3655db460e92dL1

There is some css associated to it:
https://github.com/scalacenter/scaladex/blob/master/server/src/main/assets/partials/_header.scss#L6

This is the api bit you want to use:
https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/Api.scala#L52

This is the place you want to add the GET route:
https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/Server.scala#L218

**Comment by jvican** [comment]
Hello @MasseGuillaume, thanks!
  
Just on a side note: I'm really sad we cannot use ScalaJS and that I need to do it with plain javascript.
