### ISSUE TITLE
hbase-connector for scala 2.2.17

### ISSUE THREAD

**Issue by manyasi** [scalacenter/scaladex#1230]
I am facing an issue connecting to hbase using hbase-spark-1.0.0.jar scala-library 2.12.17 and spark 3.4.0 having scala 2.12.17 and pyspark 3.4.0. I am always getting an error connecting which complaints about the scala.Product$class is not found. Looking at the scala-library 2.12.17 I can confirm that it contains only the scala.Product.class but the scala.Product$class doesn't exist. Could someone assist me with these versions so that I can achieve the task?

**Comment by adpi2** [comment]
`hbase-spark` was compiled with Scala 2.11 and so it is not compatible with Scala 2.12.

You should try to find another hbase connector that is compatible with Scala 2.12. Probably this one:
https://index.scala-lang.org/hbase-rdd/hbase-rdd
