### ISSUE TITLE
Targets and Dependencies lists not obviously useful

### ISSUE THREAD

**Issue by tpolecat** [scalacenter/scaladex#127]
I'm not sure under what circumstances I would want to browse [long] lists of projects based on compile target or dependency. Might consider at least moving keywords up to the top because it seems more useful for clicky browsing.

**Comment by heathermiller** [comment]
I agree with @tpolecat's sentiment. I think this information may be desirable in some cases to have, but the way it's currently displayed is a huge hit to usability. It's overwhelming, and more people will likely want to browse by keyword instead.

**Comment by heathermiller** [comment]
I think we can find a way to keep this information around without it being so front and center and overwhelming when first visiting the site. i.e., I think the UI side of this addition can be significantly streamlined/improved

**Comment by tpolecat** [comment]
I think things like "target" and "dependencies" might be good checkboxes to refine a search (or even sticky preferences). Also consider negative dependency filtering; for instance "don't show me anything that depends on Akka" … I think this might end up being useful.

**Comment by MasseGuillaume** [comment]
@tpolecat haha I dont know why you picked this example :eyes:

**Comment by MasseGuillaume** [comment]
@tpolecat 
[NOT dependencies:akka\/akka-actor play](https://index.scala-lang.org/search?q=NOT+dependencies%3Aakka%5C%2Fakka-actor)

**Comment by MasseGuillaume** [comment]
I'm splitting this issue into
* #140
* #288
