### ISSUE TITLE
Some pages not rendering correctly

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#128]
E.g.: https://index.scala-lang.org/andyglow/websocket-scala-client

<img width="1230" alt="screen shot 2016-07-01 at 9 13 23 am" src="https://cloud.githubusercontent.com/assets/687163/16514423/1d9247ca-3f6c-11e6-8a37-bc7586b8617f.png">

**Comment by heathermiller** [comment]
Here's yet another broken page: https://index.scala-lang.org/$ensime/ensime

**Comment by MasseGuillaume** [comment]
xml interpolation in scala is `{x}`. Dev are confused with string interpolation. see https://github.com/ensime/ensime-server/pull/1545

I think we can just remove $ from the github info

**Comment by heathermiller** [comment]
Ok, but still, two things are happening. We still have tons of pages that don't show READMES (#65)

**Comment by MasseGuillaume** [comment]
@heathermiller any example ?

**Comment by heathermiller** [comment]
Yeah, the two I provided above...

**Comment by Scyks** [comment]
Check them all locally with (#135, 136) - they work
- [x] http://index.scala-lang.org/andyglow/websocket-scala-client
- [x] http://index.scala-lang.org/andyglow/scala-xml-diff
- [x] http://index.scala-lang.org/andyglow/scala-xml-diff
- [x] http://index.scala-lang.org/ensime/ensime
- [x] http://index.scala-lang.org/ensime/java7-file-watcher
- [x] http://index.scala-lang.org/fommil/spray-json-shapeless
- [x] http://index.scala-lang.org/freetrm/eventstore-db
- [x] http://index.scala-lang.org/karasiq/nanoboard
- [x] http://index.scala-lang.org/karasiq/scalajs-marked
- [x] http://index.scala-lang.org/karasiq/scalajs-videojs
- [x] http://index.scala-lang.org/refried/macros
- [x] http://index.scala-lang.org/refried/util
- [x] http://index.scala-lang.org/softprops/stats
