### ISSUE TITLE
[Bug] JSON error message when project has no readme

### ISSUE THREAD

**Issue by bishabosha** [scalacenter/scaladex#1285]
### Current behavior

https://index.scala-lang.org/ruimo/csvparser

![Screenshot 2023-09-30 at 11 20 39](https://github.com/scalacenter/scaladex/assets/13436592/ed720257-8695-4849-aa10-8cc1f2904ba1)

Indeed the project as of writing has no readme on github

### Expected Behavior

Perhaps fill the panel with "No README found for this project, please check the repository"

### Search terms

README, error message

**Comment by adpi2** [comment]
Thanks for the report. Would you like to submit a PR? :)

**Comment by mfirry** [comment]
Could this be solved by adding something like `case HttpResponse(StatusCodes.NotFound, headers, entity, _) =>` in  [here](https://github.com/scalacenter/scaladex/blob/13ec905ae2b509b58e7c95235e17a5347552b312/modules/infra/src/main/scala/scaladex/infra/GithubClientImpl.scala#L413)?

**Comment by adpi2** [comment]
@mfirry Thanks for jumping into this. The issue is here: https://github.com/scalacenter/scaladex/blob/13ec905ae2b509b58e7c95235e17a5347552b312/modules/webclient/src/main/scala/scaladex/client/Client.scala#L43-L52

At the client side, we send a request to Github to get the readme but we don't check the status code.

**Comment by mfirry** [comment]
Ok so something along these lines would work for you?

```Scala
    fetch(request).toFuture
      .flatMap { res =>
        if(res.status == 200) {
          res.text().toFuture
        } else {
          Future("No README found for this project, please check the repository")
        }
```

**Comment by adpi2** [comment]
> Ok so something along these lines would work for you?

Yep it looks good
