### ISSUE TITLE
[Bug] sbt-scalafix not found

### ISSUE THREAD

**Issue by davesmith00000** [scalacenter/scaladex#1320]
### Current behavior

Screenshot's below.

1. Search for sbt-scalafix
2. See it in suggestions
3. Click suggestion
4. Results page shows as "Not found"

### Expected Behavior

There should be results for the [sbt-scalafix](https://github.com/scalacenter/sbt-scalafix), particularly since it is indexed sufficiently to offer it as a results suggestion.

### Extra comments

![bug-sbt-scalafix-search](https://github.com/scalacenter/scaladex/assets/908709/519506e2-971f-4847-9949-0921c2046c88)
![bug-sbt-scalafix-search-results](https://github.com/scalacenter/scaladex/assets/908709/a2544b05-d8ff-46cd-8e35-f7c80ff9f47a)

### Search terms

`sbt-scalafix`

**Comment by adpi2** [comment]
Thanks for the report! I'll look into this bug soon.

**Comment by adpi2** [comment]
It is working better: https://index.scala-lang.org/scalacenter/sbt-scalafix
