### ISSUE TITLE
Add an intermediate Artifacts page on a project

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#1337]
### Current state

On the project page, we can click on the `Versions` tab to see the list of versions of the default artifact of the project. This is fine as long as there is a single artifact in the project. But more often than not there are several artifacts in a single project and it's not obvious how to get the full list of artifacts. It is possible though by clicking on the first drop-down list in the `Versions` page.

![artifacts-page-1](https://github.com/scalacenter/scaladex/assets/13123162/69ef1ee0-c331-4a92-917f-cfc92a1fb091)

![artifacts-page-3](https://github.com/scalacenter/scaladex/assets/13123162/49fbee6c-160f-4694-a447-7087e8efd904)

### Goal

Replace the `Versions` tab by an `Artifacts` tab that lists all the artifact names of the project. Once the user clicks on an artifact it goes to the `Versions` page of that artifact.

![artifacts-page-4](https://github.com/scalacenter/scaladex/assets/13123162/351a9faf-ddb3-4680-81f9-3e627a332b10)

## Implementation Guideline

The developer can find some inspiration in:
- [artifacts.scala.html](https://github.com/scalacenter/scaladex/blob/main/modules/template/src/main/twirl/scaladex/view/project/artifacts.scala.html) for the HTML part
- [ProjectPages.scala](https://github.com/scalacenter/scaladex/blob/24f07a91e4af34d0d832df1d82147f476b1f484d/modules/server/src/main/scala/scaladex/server/route/ProjectPages.scala#L39-L77) for the endpoint (backend)
- [ArtifactTable.scala](https://github.com/scalacenter/scaladex/blob/main/modules/infra/src/main/scala/scaladex/infra/sql/ArtifactTable.scala) for the SQL part

## Expectations

- The artifacts should be grouped by latest version. By doing so it becomes clear which artifacts are newer and which are deprecated.
- There should be a option to show pre-release artifacts (`RC` or `MILESTONE` versions) as in the `Versions` tab.

**Comment by ayushkoli772** [comment]
Hello @adpi2, I'm writing to express my genuine interest in contributing to this project. I'm excited by the potential of this feature to enhance the user experience and discoverability within the platform.

I have previous experience with HTML, CSS, Javascript, Typescript, SQL and I'm actively learning Scala and have a foundational understanding of language. I understand that the project requires familiarity with Scala's "Future" library, "akka-http", and "doobie". While I haven't yet delved into these specific technologies, I'm a quick learner and eager to expand my knowledge base.

I would be grateful if you could provide some guidance on how I can best contribute to this project, given my current skillset and interest in learning. Additionally, any pointers to resources that can help me familiarize myself with the existing codebase and install this locally.

Thank you for your time and consideration. I look forward to hearing from you soon and potentially contributing to this exciting project.

**Comment by adpi2** [comment]
@ayushkoli772 Thanks for expressing your interest in contributing to this project. We are very much looking forward to new contributors.

Am I correct to assume that you will apply to [Google Summer of Code](https://github.com/scalacenter/GoogleSummerOfCode)? Or do you prefer to contribute on your own?

> Additionally, any pointers to resources that can help me familiarize myself with the existing codebase and install this locally.

We have a [contributing guide](https://github.com/scalacenter/scaladex/blob/main/CONTRIBUTING.md) to share information on how to contribute to this project. In particular you can install the [needed tools](https://github.com/scalacenter/scaladex/blob/main/CONTRIBUTING.md#requirements) and  follow the steps [here](https://github.com/scalacenter/scaladex/blob/main/CONTRIBUTING.md#setting-up) to clone and install the project for the first time. It is easier to run the project if you have [docker](https://docs.docker.com/engine/install/) on your machine. Otherwise you will need to install and manage a local instance of PostgreSQL and Elasticsearch.

If you have any trouble, you can reach out to me on Discord with my username `adpi2`. If you need help with Scala you can also ask questions on the [Scala discord channel](https://discord.com/invite/scala).

**Comment by MAVRICK-1** [comment]
@adpi2 is this still open? Can you assign me this?

**Comment by adpi2** [comment]
@MAVRICK-1 This project is part of [Google Summer of Code (GSOC)](https://summerofcode.withgoogle.com/). If you want to participate as a contributor, you need to register on the GSOC website. Contributors application will open on Monday, March 18, 2024 at 18:00 UTC. You'll find more information on this [blogpost](https://opensource.googleblog.com/2024/02/mentor-organizations-announced-for-google-summer-of-code-2024.html).

**Comment by adpi2** [comment]
Hello all, if you want to apply for this GSOC project please send me an email. You can find all the details [here](https://github.com/scalacenter/GoogleSummerOfCode#scaladex-new-artifact-page).

**Comment by ayushkoli772** [comment]
@adpi2 This issue is resolved in #1447 

Will it be fine if I close this?
