### ISSUE TITLE
Extract the "Dependencies" list from the front page.

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#140]
Following up on #127; rather than having stuff like the dependencies list on the front page, perhaps we should make something like a "Browse" page where we list all such information? 

This way we can keep the front page a bit more streamlined?

**Comment by MasseGuillaume** [comment]
* [ ] I think we could use it as a sorting field in the search result page. 
* [ ] We can also add another section to the front page, currently we have "Recent Projects" and "Recent Releases". It would make sense to add a section "Most depended-upon packages" (see npmjs: https://www.npmjs.com/#pane-most-depended-upon)
