### ISSUE TITLE
[Bug] Impossible to edit Contributing Info

### ISSUE THREAD

**Issue by ghostdogpr** [scalacenter/scaladex#1400]
### Current behavior

I am trying to edit Contributing Info by adding links to Contributing Guide, Code of Conduct and Chatroom, but it doesn't have any effect when I click Update, the data stays empty. I tried for this project https://index.scala-lang.org/ghostdogpr/caliban

<img width="1099" alt="Screenshot 2024-05-16 at 11 51 34 PM" src="https://github.com/scalacenter/scaladex/assets/7413894/ab2253eb-03c8-4ab7-a5bf-2778f9d2d031">

### Expected Behavior

Changes are recorded

**Comment by adpi2** [comment]
Thanks for opening this issue.

**Comment by adpi2** [comment]
Since we can get the chatroom, code of conduct and contributing guide from the Github API, I am going to remove those fields from the project setttings.
