### ISSUE TITLE
[Bug] Several artifact pages are currently broken ('Not found')

### ISSUE THREAD

**Issue by rtyley** [scalacenter/scaladex#1405]
### Current behavior

Not working:

- https://index.scala-lang.org/guardian/play-secret-rotation
- https://index.scala-lang.org/guardian/marley

 ...despite `guardian/marley` being returned in [search results](https://index.scala-lang.org/guardian):

![image](https://github.com/scalacenter/scaladex/assets/52038/5648db2c-0365-4044-be2e-e755c8c2f579)

...the [artifact page itself](https://index.scala-lang.org/guardian/marley) is 'Not found':
![image](https://github.com/scalacenter/scaladex/assets/52038/74088437-dcae-41e5-8d55-52b220bfef25)

Works:

https://index.scala-lang.org/typelevel/cats
https://index.scala-lang.org/scalaz/scalaz
https://index.scala-lang.org/playframework/playframework
https://index.scala-lang.org/guardian/content-api-scala-client

### Expected Behavior

The pages should be found.

**Comment by felher** [comment]
Just stumbled upon this too. The scope of the problem might be larger than it seems at first. I tested some queries and counted how many on the first page could not be found:

|query|number tested|down|
|-|-|-|
|raquo|11|7|
|akka|20|4|
|cats|20|12|
|http4s|20|6|
|zio|20|7|

This was done by hand, so maybe it is a bit off and the the sample size isn't large, but rough estimates, about 40% of Scaladex projects might be currently "not found".

**Comment by spamegg1** [comment]
I had the issue with [libraries from `com-lihaoyi`](https://users.scala-lang.org/t/scaladex-cannot-find-some-result-pages/10022)

**Comment by adpi2** [comment]
Hello all, thanks for opening this issue. This seems like a serious regression and I will try to solve it today.

**Comment by rtyley** [comment]
Thanks @adpi2 !
