### ISSUE TITLE
Broken search?

### ISSUE THREAD

**Issue by slandelle** [scalacenter/scaladex#141]
Hi there,

I'm the lead project of [Gatling](https://github.com/gatling/gatling).
When [searching for "gatling" in Scaladex](https://index.scala-lang.org/search?q=gatling), only some children projects get listed, not the main one (which should definitively be the most relevant one for this keywork).

From scaladex-data's README, I understand that our project should be automatically listed as it's published on central and does have an [scm](https://repo1.maven.org/maven2/io/gatling/gatling-parent/2.2.2/gatling-parent-2.2.2.pom) tag pointing to its Github repository.

Do I get it wrong? How could I fix it?

Thanks!

**Comment by Scyks** [comment]
Hey,

i just investigated your problem, and indeed it's not indexed at all. You're right, as mentioned all Scala artifacts get indexed automatically when they follow the standard or publishing to maven. To find artifacts which are build in Scala, the indicator is the Scala version in the end of the artifact id `gatling-http_2.11`.

You could easily fix that by adding the Scala version to your build like `gatlingModule("gatling-http" + scalaVersion)` 

If you do so, we'll index your artifact automatically. But then, there will be the problem that all your currently released artifacts are not index at all. We could implement a json list of previous versions to index them also.

````
[
    "io.gatling.gatling-http.2.2.0",
    "io.gatling.gatling-app.2.2.0",
    ...
]
```

Of course we need to implement that in the indexing process. I expect that also other libraries have kind of the same problem, so it's good to provide a solution.

Best
Ronald

**Comment by heathermiller** [comment]
🎉 🍻 #145 courtesy of the talented @Scyks 💃

**Comment by Scyks** [comment]
haha, thanks :) @heathermiller

**Comment by slandelle** [comment]
@Scyks Thanks for investigating and explaining.

Not appending the Scala version is intended.

We don't plan to ever cross compile, and we aim to have Gatling used outside the sole Scala community. Scala versioning scheme is lost on most non-Scala developers, so we'd rather keep things simple for them and stick to the maven model, at least for now.

I can provide you with any PR you want with a list of our artifacts.
Please let me know.

Thanks a lot

Stéphane

**Comment by Scyks** [comment]
@slandelle

Okay, this means also that we need a wildcard for versions when you don't want to add the scala version.
I need to implement this then also and I need to write a documentation how to index these kind of projects.

It would be nice if you could provide your artifact list. If you want to prepare that please use the described syntax above.

If the stuff is merged and described, i'll let you know to provide the PR.

Best
Ronald

**Comment by Scyks** [comment]
@slandelle The documentation is ready.
https://github.com/scalacenter/scaladex-data#index-artifacts-which-are-published-in-java-style

You can create a PR now for your artifacts. But still we need to merge and finish #141 to make it work.

**Comment by slandelle** [comment]
@Scyks Done, thanks! https://github.com/scalacenter/scaladex-data/pull/4

**Comment by Scyks** [comment]
@slandelle The format isn't correct, but @MasseGuillaume will fix it. You need to know also, that now alls version >=2.2 get's index, but *not* any older version.

For that you need to add these version also by creating a new PR. If you're okay with that, it should work from the next release and reindexing.

**Comment by slandelle** [comment]
> The format isn't correct, but @MasseGuillaume will fix it.

Sorry for this. Thanks for fixing.

> You need to know also, that now alls version >=2.2 get's index, but not any older version.

Yep, I'm fine with that.

**Comment by Scyks** [comment]
@slandelle It's live https://index.scala-lang.org/gatling

**Comment by slandelle** [comment]
Awesome, you guys rock!
