### ISSUE TITLE
Show Sbt/Maven coordinates?

### ISSUE THREAD

**Issue by yamin-oanda** [scalacenter/scaladex#1424]
Hi, I think at one point the Maven coordinates of packages were shown, eg #81

But now it looks like this is no longer shown. Could it be added back? It would be great if there was a 'copy to clipboard' button so we could easily copy the coordinates to the clipboard for pasting.

**Comment by adpi2** [comment]
Hi @yamin-oanda, the Maven coordinates and copy button are still there but you have to chose a precise artifact and version of the project to get to it.

Example: https://index.scala-lang.org/typelevel/cats/artifacts/cats-core/2.12.0
