### ISSUE TITLE
[Bug] Scaladex site is returning HTTP 503  responses

### ISSUE THREAD

**Issue by rtyley** [scalacenter/scaladex#1429]
### Current behavior

Responses on https://index.scala-lang.org/ are currently eventually timing out with an HTTP 503 (Service Unavailable) error:

```
The server was not able to produce a timely response to your request.
Please try again in a short while!
```

![image](https://github.com/user-attachments/assets/59e4cfbe-f70b-4d38-8a6c-b556593c3210)

### Expected Behavior

HTTP 200!

**Comment by adpi2** [comment]
Scaladex is again returning many timeouts. I am working on it.

**Comment by rtyley** [comment]
Hope it's not too intractable as an issue - good luck!

For myself as an outsider, if you ever have time to share your findings on the outage, it would be interesting to hear them! If there is any issue in the codebase I could usefully work on, I'd be interested to know about it- or even if it's hosting costs/limitations, that would be interesting too.
