### ISSUE TITLE
Pagination broken

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#146]
<img width="555" alt="screen shot 2016-07-03 at 5 17 21 pm" src="https://cloud.githubusercontent.com/assets/687163/16546156/104aa3c8-4142-11e6-8f71-d5caae9ccd10.png">

**Comment by heathermiller** [comment]
The query: `dependencies:playframework\/play-ws`

**Comment by Scyks** [comment]
Maybe we could fix the naming then also: Page N of X Results it's not understandable.
I suggest something like: `Page N of X - Y Results`

**Comment by MasseGuillaume** [comment]
But that's how Google does it ! :P

**Comment by MasseGuillaume** [comment]
I think there is a regression in 1023a68985fd7b5a9dae89ffcef719a84ccc5c26.

https://index.scala-lang.org/search?q=dependencies:slick\/slick&page=2
shows 1 ~ 11

https://index.scala-lang.org/search?q=dependencies:slick\/slick&page=3
show 1 ~ 6
