### ISSUE TITLE
The package dropdown doesn't work anymore

### ISSUE THREAD

**Issue by Scyks** [scalacenter/scaladex#148]
On https://index.scala-lang.org/akka/akka-actor there is package select box and a version select box. 
both does now go to the organization page instead of selecting the version or the package.

https://index.scala-lang.org/akka?artifact=akka-actor-tests

**Comment by MasseGuillaume** [comment]
ok I'm on it

**Comment by heathermiller** [comment]
Let's try to cross-reference issues and PRs, just for the sake of archaeology later if we stumble upon some kind of regression. It's always easier when code changes are linked to issues this way.

Resolved by #149
