### ISSUE TITLE
Index private repositories

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#15]
[Eugene Platonov at ebay](https://www.linkedin.com/in/jozic) said it would be helpful to index private repos. For example, they could look for reverse dependencies to notify them for breaking api changes.

**Comment by MasseGuillaume** [comment]
Currently we discover and download POM from Bintray. It would be possible to use Sonatype api to index private repositories implementing the following:
* [discover poms](https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/bintray/ListPoms.scala)
* [download poms](https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/bintray/DownloadPoms.scala)
* [download parent poms](https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/bintray/DownloadParentPoms.scala)

We also use the scm tag to create the notion of project. A project is equivalent to a Github repository. If not hosted on Github. A private repository would have to find another hypothesis to group projects.

* [group releases by projects](https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/project/ProjectConvert.scala#L116)
* [download project info](https://github.com/scalacenter/scaladex/tree/master/data/src/main/scala/ch.epfl.scala.index.data/github) (README, contributors, issues, etc)
* [display project info](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/artifact.scala.html)

**Comment by MasseGuillaume** [comment]
more info at https://gitter.im/scalacenter/scaladex?at=577bb5d6584c2e775be65015

**Comment by Scyks** [comment]
This could be solved by #176. I tested that already and it works if the private repository is on GitHub. It might be also possible to use GitLab / Bitbucket later.

Also with #176, it might be possible to have an internal scaladex running.

**Comment by Scyks** [comment]
With #176 this task is partly done. The SBT Plugin allows you to index private GitHub repositories now. This could also be used or internal copy of Scaladex. The main information how to do that is already in the [Readme](https://github.com/scalacenter/scaladex/blob/master/README.MD).

To index old releases you could also publish them using the SBT-Plugin. It might be a bit work put it's possible.

Happy Indexing :)
