### ISSUE TITLE
Non standard deployed libs have a wrong URL in dependents

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#155]
cc/ @Scyks

**Comment by MasseGuillaume** [comment]
do you have an example ?

it look like it works for
https://index.scala-lang.org/gatling/gatling-core

will point to

https://index.scala-lang.org/gatling/gatling-metrics/2.2.2

**Comment by Scyks** [comment]
Strange. I checked that twice and was not working. I tested with scala-Library.

**Comment by heathermiller** [comment]
Same here, it was worse for me this morning – none of the gatling projects had any dependents at all listed when I opened this ticket. So I of course couldn't test any links... Maybe elasticsearch was burping under the hood this morning? /shrug

**Comment by Scyks** [comment]
Good that it's not an issue, maybe i mixed something up with Java Dependencies. Sorry for confusing you.
