### ISSUE TITLE
Scodec links to wrong page

### ISSUE THREAD

**Issue by Fristi** [scalacenter/scaladex#161]
https://index.scala-lang.org/search?q=scodec "scodec" seems to link to https://index.scala-lang.org/scodec/scodec-core/1.9.0 which is broken

**Comment by MasseGuillaume** [comment]
it's based on http://search.maven.org/#artifactdetails%7Corg.scodec%7Cscodec-core_2.11%7C1.8.0%7Cbundle

```xml
<scm>
  <url>git@github.com:scodec/scodec-core.git</url>
  <connection>scm:git:git@github.com:scodec/scodec-core.git</connection>
</scm>
```

the 4th link I see is https://index.scala-lang.org/scodec/scodec-core and points to 1.8.0

**Comment by MasseGuillaume** [comment]
One way to fix this would be to give precedence to [claims.json](https://github.com/scalacenter/scaladex-data/blob/master/claims.json) over pom data.

**Comment by Fristi** [comment]
Pinging @mpilquist.

**Comment by MasseGuillaume** [comment]
I think it was a publishing error and https://github.com/scodec/scodec-core never existed

**Comment by Scyks** [comment]
This is fixed by https://github.com/scalacenter/scaladex-data/pull/5

**Comment by MasseGuillaume** [comment]
https://github.com/scalacenter/scaladex/issues/162#issuecomment-230356878

**Comment by mpilquist** [comment]
FYI, this was a publishing error in scodec-core, which was fixed last July in https://github.com/scodec/scodec/commit/f35cd91b.
