### ISSUE TITLE
claims.json should have precedence over pom information

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#162]
this way we can fix pom publishing errors like #161

**Comment by Scyks** [comment]
I guess this was a miss understanding. It works already. It was fixed by #134 and PR #135.

**Comment by Scyks** [comment]
I added `"org.scodec scodec-core_*": "scodec/scodec"` to [claims.json](https://github.com/scalacenter/scaladex-data/blob/master/claims.json) reindexed and it works.

<img width="1269" alt="scodec" src="https://cloud.githubusercontent.com/assets/875242/16569688/73e229cc-4239-11e6-9b9d-a19c791fc390.png">

**Comment by MasseGuillaume** [comment]
[headOption on Set](https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/project/ProjectConvert.scala#L81) can give any ordering
