### ISSUE TITLE
render Issue on artifact pages (stats, contributors)

### ISSUE THREAD

**Issue by Scyks** [scalacenter/scaladex#168]
During all the moving of "github Stats block" and "contributors" block on the artifact page they now get rendered multiple times.

The right block is in a loop of Scala targets, but the Github stats and contributors does not change at all. This could be a small performance impact on the pages to just render it once.

**Comment by heathermiller** [comment]
Oh no! Maybe something I did caused this. Do you have an example page where this is occurring? I just searched around and couldn't find anything

**Comment by Scyks** [comment]
It's on every page ;)

**Comment by heathermiller** [comment]
It's not happening for me on what's currently deployed on index.scala-lang.org

**Comment by Scyks** [comment]
have a look at https://index.scala-lang.org/apache/spark-hive
<img width="409" alt="render" src="https://cloud.githubusercontent.com/assets/875242/16576774/9cc8e01c-4291-11e6-8f35-ce374947b4f3.png">

**Comment by Scyks** [comment]
merged, can be closed.
