### ISSUE TITLE
README troubles again

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#184]
In the currently-deployed Scaladex, we're missing the README in some places again. For example, in https://index.scala-lang.org/guardian/scanamo-scrooge

<img width="1205" alt="screen shot 2016-07-14 at 8 45 57 am" src="https://cloud.githubusercontent.com/assets/687163/16830463/691807b0-499f-11e6-8f93-adb864437204.png">

**Comment by heathermiller** [comment]
<img width="1233" alt="screen shot 2016-07-14 at 5 50 53 pm" src="https://cloud.githubusercontent.com/assets/687163/16846138/8faecd40-49eb-11e6-97df-f9ffb0cbddc3.png">
<img width="1224" alt="screen shot 2016-07-14 at 5 53 32 pm" src="https://cloud.githubusercontent.com/assets/687163/16846244/e8aeb216-49eb-11e6-851b-d3207c759b52.png">

**Comment by heathermiller** [comment]
:(

**Comment by Scyks** [comment]
for `cgta/autowire` the repository does not exist https://github.com/cgta/autowire
for `akka-wamp/akka-wamp` the same https://github.com/akka-wamp/akka-wamp
for `guardian/scanamo-scrooge` it should be there.

@MasseGuillaume are you also downloading new GitHub info during deployment?

**Comment by MasseGuillaume** [comment]
@Scyks will look

**Comment by MasseGuillaume** [comment]
@Scyks guardian/scanamo-scrooge should be in now :-)

**Comment by heathermiller** [comment]
Why was this closed?

**Comment by MasseGuillaume** [comment]
@heathermiller fixed in https://github.com/scalacenter/scaladex-poms/commit/6e509ee74de0113705f6cef0a4939ce471443f5c

**Comment by heathermiller** [comment]
It's still not fixed.

**Comment by heathermiller** [comment]
eg: https://index.scala-lang.org/dylemma/xml-spac

**Comment by MasseGuillaume** [comment]
this is fine now locally
