### ISSUE TITLE
Increase in number of dropdown menus getting confusing. UI also broken

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#185]
At this point, having 3 different drop-down menus has gotten confusing. It's also beginning to break the UI :(

<img width="409" alt="screen shot 2016-07-14 at 8 47 22 am" src="https://cloud.githubusercontent.com/assets/687163/16830486/a92b74d6-499f-11e6-96c9-dd0b2f6c6eaf.png">

I have some ideas for how to clarify this, in a UI sense... (Crazy busy with SC tasks and then organizing a conference next week, but can pick it up shortly after)

**Comment by MasseGuillaume** [comment]
What's confusing ?

When you select a software you have to make sure it match you requirements. For example the elastic4s project propose different versions based on the elasticsearch version:
https://github.com/sksamuel/elastic4s#release

I added a PR to improve the default selection https://github.com/scalacenter/scaladex/pull/187. You can take a look at the heuristic here: 
https://github.com/scalacenter/scaladex/pull/187/files#diff-f858c9753a8852831556f8a3e4ca3985R48

**Comment by heathermiller** [comment]
I just think that the UI can be clarified. No worries, I have an idea of how we can do this :)

**Comment by MasseGuillaume** [comment]
#e6a79eb44d479890c3e43c63c5e3e3bfc37ad032
