### ISSUE TITLE
Organization pages broken now

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#186]
Try going to any organization page. Now you get: "The requested resource could not be found."
E.g., https://index.scala-lang.org/twitter

**Comment by MasseGuillaume** [comment]
it's now at https://index.scala-lang.org/search?q=organization%3Atwitter

The advantage it's that it's accessible directly via the search. If you wish we could keep the old url.

**Comment by heathermiller** [comment]
I'd like to keep the old URL. I'd rather this be like github, where one just has to do:

github.com/orgname

...and can just see the list of projects under that organization

**Comment by heathermiller** [comment]
Is there some way to get both? Search and nice URL?
