### ISSUE TITLE
Adopt scalafmt

### ISSUE THREAD

**Issue by jvican** [scalacenter/scaladex#188]
Hello, given the success of the project and that some parts of the codebase are not very well formatted, I would propose to adopt scalafmt. I think it's a very good tool that works reliable, plus it's developed by one of the SC guys.
  
If you agree on this, I'll make a PR with it.

**Comment by MasseGuillaume** [comment]
@jvican go for it, I hope it does a good job with the akka-http routing dsl :P

**Comment by jvican** [comment]
I've run scalafmt, and I'm getting a weird error that apparently happens because of a scala 2.10 compatibility issue (see [this](http://stackoverflow.com/questions/25089852/what-is-the-reason-for-java-lang-nosuchmethoderror-scala-predef-arrowassoc-upo)).
  
I run scalafmt with sbt in the root project. It crashes when formatting the server:
```
[info] Resolving org.scala-lang#scalap;2.11.8 ...
[info] Done updating.
[info] Updating {file:/data/rw/code/scala/scaladex/}server...
[info] Resolving com.typesafe.play#twirl-api_2.11;1.1.1 ...
[info] Formatting 27 Scala sources {file:/data/rw/code/scala/scaladex/}data ...
[info] Resolving org.scala-lang#scalap;2.11.8 ...
[info] Done updating.
[info] Formatting 6 Scala sources {file:/data/rw/code/scala/scaladex/}server ...
[trace] Stack trace suppressed: run last sbtScaladex/compile:scalafmt for the full output.
[error] (sbtScaladex/compile:scalafmt) java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
[error] Total time: 8 s, completed Jul 15, 2016 9:23:28 PM
```
/ping @olafurpg 
  
Are you using scala 2.10 somewhere in the project aside from sbtScaladex?

**Comment by MasseGuillaume** [comment]
only the sbt plugin

**Comment by olafurpg** [comment]
This is a known issue with the sbt scalafmt plugin, see
https://github.com/olafurpg/scalafmt/issues/190

Since it seems many are affected but it, I'll try to take a look at it when
I find time.

**Comment by jvican** [comment]
Thanks @olafurpg, there's no rush, though, we can live without it for now.

**Comment by MasseGuillaume** [comment]
#205
