### ISSUE TITLE
sbt plugins & ivy dependencies

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#191]
sbt plugins are published via ivy

https://bintray.com/sbt/sbt-plugin-releases

https://bintray.com/scaladex/sbt-plugins/sbt-scaladex#files/ch.epfl.scala.index/sbt-scaladex/scala_2.10/sbt_0.13/0.1.3/ivys

doc: http://ant.apache.org/ivy/history/latest-milestone/ivyfile.html

**Comment by dwijnand** [comment]
:+1:

We'll probably be able to retire/decommission http://www.scala-sbt.org/0.13/docs/Community-Plugins.html if/when this ships.
