### ISSUE TITLE
Don't make `data/reStart elastic` async...

### ISSUE THREAD

**Issue by jvican** [scalacenter/scaladex#194]
Or if you do, redirect the output since after the task is executed it starts to pollute the sbt output.

**Comment by MasseGuillaume** [comment]
you mean you want to attach reStart task to the sbt console ?

**Comment by jvican** [comment]
Well, if it's possible we execute the task but we wait until it's complete. If you prefer to run it in the background, we redirect the output to a file.

**Comment by MasseGuillaume** [comment]
I'm not sure I understand can you give me an actual vs expected result ?

**Comment by jvican** [comment]
When I run the task, it runs in the background (which means I can type whatever sbt command I want in the meanwhile). What I want to do is either to run it in the foreground, or to redirect the output (because when I run the task, all output starts to appear in the sbt console while I'm typing other commands).

**Comment by MasseGuillaume** [comment]
I dont think it's possible.

This is what we can configure: http://www.scala-sbt.org/0.13/docs/Forking.html#Configuring+output

**Comment by jvican** [comment]
Then let's make it run in the foreground :smile:

**Comment by MasseGuillaume** [comment]
oh nvm : `connectInput`

**Comment by MasseGuillaume** [comment]
https://github.com/spray/sbt-revolver/blob/40783737b1ad64a35dc9b2cb726d21603ad3c80e/src/main/scala/spray/revolver/RevolverPlugin.scala#L84

**Comment by MasseGuillaume** [comment]
then `run elastic`
