### ISSUE TITLE
write elasticsearch data in sbt's target folder

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#197]
/cc @jvican

**Comment by jvican** [comment]
You taking care of this? I could do it pretty quickly.

**Comment by heathermiller** [comment]
You can do eet!

**Comment by MasseGuillaume** [comment]
fixed in 968e8ec84fb956b168fce16fe6a2989bd87ac5d9 sorry !

**Comment by MasseGuillaume** [comment]
This is problematic when deploying however (it would point to my project directory in alaska). I have a branch https://github.com/scalacenter/scaladex/tree/feature/deploy for this topic

**Comment by jvican** [comment]
Oh, true, I was kinda suprised that didn't work before with those lines before. It turned out I rebased and got your new results.
