### ISSUE TITLE
indexing transferred projects

### ISSUE THREAD

**Issue by sullivan-** [scalacenter/scaladex#200]
I just logged in to Scaladex for the first time and added some repositories. The longevity project used to be hosted on GitHub here: `https://github.com/sullivan-/longevity`. A few artifacts (up to 0.2.0) were published from the repository at this location. I've since transferred ownership of this repository to here: `https://github.com/longevityframework/longevity`. When I search for longevity on Scaladex, I see the new project, but I also see this one, which is sort of a mishmash of the project at the old location, and the project at the new location:

https://index.scala-lang.org/sullivan-/longevity

I think this is happening because it is reflecting artifacts published from the old GitHub location, but the old GitHub location now redirects to the new one.

It seems like it will be kind of confusing for both of these projects to turn up in a search for term "longevity". I wish the new site would be reflected and not the old.

Possibly related, the project here:

https://index.scala-lang.org/longevityframework/longevity

Shows a most recent release of 0.5.0, but I just published 0.9.0 last week.

**Comment by MasseGuillaume** [comment]
you can claim all longevity releases in https://github.com/scalacenter/scaladex-data

this has precedence over pom informations.

you published old artifacts under:

groupId: net.jsmscs
artifactId: longevity_*

add the following line to claims.json

```
"net.jsmscs longevity_*": "longevityframework/longevity",
```

this will remove `sullivan-/longevity` from the index.

For the new release (0.5.0), I have it locally, I will reindex now.

**Comment by sullivan-** [comment]
Thank you! I just submitted a pull request for the claim.

**Comment by MasseGuillaume** [comment]
@sullivan- 

https://index.scala-lang.org/sullivan-/longevity does not exists anymore
https://index.scala-lang.org/longevityframework/longevity contains release 0.5.0 and older longevity releases (0.2.0 downward)

**Comment by sullivan-** [comment]
thanks Guillaume! but my latest release is 0.9.0 😁..

**Comment by MasseGuillaume** [comment]
ok 0.9.0 was published the 15th of Jully.
http://search.maven.org/#search%7Cga%7C1%7Corg.longevityframework

We use Bintray to discover poms. They have a ~3 days delay on maven central
https://bintray.com/api/v1/search/file?name=longevity_2.11-0.9.0.pom
It look like it was transfer today: `"created":"2016-07-19T04:04:45.860Z"`

We are developing a sbt plugin to make the process faster. It should be available soon.

**Comment by sullivan-** [comment]
okay, makes sense. thanks again!

**Comment by sullivan-** [comment]
Just to note, longevity is still showing version 0.5.0 on Scaladex, when the latest version is actually 0.9.0. Thanks.

**Comment by MasseGuillaume** [comment]
your scmInfo
https://github.com/longevityframework/longevity/blob/master/project/LongevityBuild.scala#L47-L48

is pointing to
https://github.com/longevityframework/emblem

see
https://index.scala-lang.org/longevityframework/emblem

**Comment by sullivan-** [comment]
Oops! Thanks for pointing that out. I just committed a fix.

Yeah, I can see the longevity artifacts on the emblem Scaladex page.
