### ISSUE TITLE
Organization pages broken again, they show more than org's projects

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#210]
E.g., if you check the Twitter organization on Scaladex, you'll see that there are 3162 results for projects. 

https://index.scala-lang.org/twitter

<img width="504" alt="screen shot 2016-07-21 at 10 55 15 am" src="https://cloud.githubusercontent.com/assets/687163/17016939/a41dce66-4f31-11e6-8878-bb7ffdb91aa7.png">

**Comment by MasseGuillaume** [comment]
solved in 40f13ed60ba12c28bdab9da58bcebe7f07c3b5cc
