### ISSUE TITLE
default version override

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#222]
/cc @jducoeur

https://index.scala-lang.org/jducoeur/jquery-facade

Select 0.11 by default. @jducoeur would prefer to enfore 1.0-RC6

**Comment by MasseGuillaume** [comment]
@jducoeur

The issue with setting a default version is to have stalled data. The data pipeline will fetch new data but the library author may forget to update the version on the index.

Instead of selection a specific version we will provide a way to select a default version strategy: latest or stable.

stable will be the last non pre release version if it exists and latest will be the latest version.

**Comment by jducoeur** [comment]
Sounds like a reasonable strategy...

**Comment by MasseGuillaume** [comment]
@jducoeur we just enable continuous delivery, this feature will be deployed in a couple minutes ;-)

**Comment by jducoeur** [comment]
Excellent!
