### ISSUE TITLE
Fuzzy search: match on substrings

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scaladex#228]
I really like the new auto-completion list that pops up while I type my search query. However, I noticed that the results don't make sense until I type out the full name of what I'm looking for. For example, searching ["scalafm"](https://index.scala-lang.org/search?q=scalafm) yields 0 results. olafurpg/scalafmt only appears if the query is "scalafmt" verbatim.

Other examples:

- "test" doesn't list scalatest
- "pars" yields 0 results
- "jso" yields 0 results

Without fuzzy search, it can be difficult to find stuff because most of the time you don't know the exact full name of what your looking for.

**Comment by MasseGuillaume** [comment]
I'm using fuzzy search locally all those cases works with the exception of scalatest
