### ISSUE TITLE
Documentation links appear to be broken

### ISSUE THREAD

**Issue by jducoeur** [scalacenter/scaladex#234]
At the moment, when I go to one of my projects and click the "Scaladocs" link, it takes me right back to the page I'm looking at.

Not sure when this changed -- I'm pretty sure it was working last week.  (And I think it's one of the lovelier features.)

**Comment by MasseGuillaume** [comment]
I should clear the link when it's empty in the interim I used the default link:

https://www.javadoc.io/doc/[groupId]/[artifactId]/[version]
