### ISSUE TITLE
twitter card per project

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#239]
On a project page the twitter card should display it's logo

/cc @alexandru

**Comment by julienrf** [comment]
For reference here the link that explains the expected format: https://twitter.com/alexelcu/status/762998231626383360

**Comment by julienrf** [comment]
What values should we use for the following fields?
- The Twitter @username the card should be attributed to ;
- The description (when absent).

**Comment by alexandru** [comment]
- The Twitter username should be @scala_lang. It's only used for analytics stuff I believe.
- the one line description you fetch from GitHub per project is perfect for the description

**Comment by MasseGuillaume** [comment]
This is where to look:
* [general html template for a page where we can add `head` tags](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/main.scala.html#L3)
* [project page html template](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/project/project.scala.html#L10)

**Comment by heathermiller** [comment]
Woohoo!! 🎉 🍻 🍷 🎉 
Thank you @lunaryorn!

**Comment by MasseGuillaume** [comment]
Deploying now ;-)

**Comment by lunaryorn** [comment]
@heathermiller You're welcome :blush:
