### ISSUE TITLE
Adding a DuckDuckGo "bang" integration

### ISSUE THREAD

**Issue by mikolak-net** [scalacenter/scaladex#248]
Out of curiosity, I've searched for it, and [it seems to be missing](https://duckduckgo.com/bang?q=scala) .

Adding a [bang integration](https://duckduckgo.com/bang) to DuckDuckGo would be a "cheap" way to increase awareness of ScalaDex.

[The form](https://duckduckgo.com/newbang) is relatively straightforward. There remain two open points:
- the "bang" mnemonic (Maven Central uses `mvn` by way of comparison),
- the exact query string template.

**Comment by julienrf** [comment]
Thanks for the suggestion!

> - the "bang" mnemonic (Maven Central uses `mvn` by way of comparison)

`scala` is already used for scala-search.org. `scalalib`?

> - the exact query string template.

https://index.scala-lang.org/search?q={{{s}}}

**Comment by mikolak-net** [comment]
@julienrf: sure thing.

Re mnemonic: perhaps just `scaladex`, and an additional shorter alias (I would propose `scd`, but that's already taken by _Science Daily_ :p ).

Re query: OK, so basically the standard query? (aside - the example template URL, when accessed directly, returns a 500 error :) )

**Comment by MasseGuillaume** [comment]
@mikolak-net @julienrf I will contact scala search to kindly ask to transfer their bang command

**Comment by julienrf** [comment]
@MasseGuillaume But then what will scala-search use?

**Comment by MasseGuillaume** [comment]
scala-search :)

**Comment by mikolak-net** [comment]
Well, that's one way to go :).

**Comment by mikolak-net** [comment]
@MasseGuillaume : I see that now `!scala` leads to `docs.scala-lang.org`. Was this the intent of your request to Lukas, or is it just a consequence of one of Our Benefactors stumbling upon this issue ;)?

Regardless, we're now back to square one (as the current `!scala` makes complete sense). So, `!scaladex` with a shorter alias - sounds good?

**Comment by MasseGuillaume** [comment]
yep !scaladex is fine ;)

**Comment by MasseGuillaume** [comment]
I just added scaladex ;-)

**Comment by mikolak-net** [comment]
Great, might I also suggest an alias such as "!scx" for those of us skimping on their keyboard switches ;)?

**Comment by MasseGuillaume** [comment]
strange it's still not available

**Comment by mikolak-net** [comment]
TBH, no idea how long that takes them usually. Maybe it just hit the top of the next buffer frame or something ;).

**Comment by MasseGuillaume** [comment]
done :-) [https://duckduckgo.com/?q=!scaladex akka](https://duckduckgo.com/?q=!scaladex akka)
