### ISSUE TITLE
Non web resources should not be exposed

### ISSUE THREAD

**Issue by takezoe** [scalacenter/scaladex#251]
Akka-HTTP's `getFromResource()` exposes all resources in classpath. In [this commit](https://github.com/scalacenter/scaladex/commit/4a2e4d8f3a1137c591bddf7ae08a6d0e617b6566), `reference.conf` was blocked, however we can still access to other resources in classpath includes all dependent jar files. For example, we can access `logback.xml` as a following URL:
https://index.scala-lang.org/assets/logback.xml

IMHO, resources which should be exposed are bunched up under the specific package and the server should retrieve resource for request to `assets/*` from under that package.

**Comment by MasseGuillaume** [comment]
* this is [the culpit]( https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/Server.scala#L387-L388)
* [this is why webjars are available on the classpath](https://github.com/scalacenter/scaladex/blob/master/build.sbt#L92)

this is what should be accessible:
* [javascript from webjars](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/main.scala.html#L113)
* [javascript from Scala.js](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/main.scala.html#L105-L111)
* [images in resources folder](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/main.scala.html#L40)
* [less compilation css product](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/main.scala.html#L17)

one way to solve it without touching sbt would be to allow anything in: `lib/`, `img/` or files: `main.css`, `client-jsdeps.js`, `client-opt.js` and `client-fastopt.js`

**Comment by MasseGuillaume** [comment]
fixed in d00d18d6060d0e235b7a4108d49512a8e5d8a518
