### ISSUE TITLE
Not possible to see pages 2 and 3 of my projects

### ISSUE THREAD

**Issue by Sciss** [scalacenter/scaladex#254]
So if I log in and click projects, it say I have 53 published projects. Page 1 is fine: https://index.scala-lang.org/search?q=you&you (but note the strange `you&you`; but if I click on page 2 at the end of this page, I get an invalid URL: https://index.scala-lang.org/search?q=youyou&page=2 (note the `youyou`). If I try to manually correct URL to https://index.scala-lang.org/search?q=you&page=2 - I get a selection random projects, none of which is mine. This is with Firefox 45.

**Comment by MasseGuillaume** [comment]
Thanks for reporting the bug ;-)

as a workaround you can use https://index.scala-lang.org/sciss?q=organization:sciss&page=1

**Comment by MasseGuillaume** [comment]
something is wrong here: https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/searchresult.scala.html#L13

**Comment by MasseGuillaume** [comment]
solved in https://github.com/scalacenter/scaladex/pull/269
