### ISSUE TITLE
Show contributors count & filter by contributors

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#271]
The number of contributors is a good metric for a healthy open source project. We can show contributor count in the search result list and add a search sorting field based on the contributors.

search result list at: https://index.scala-lang.org/search?q=
- [ ] show contributor count
  - [html template](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/searchresult.scala.html)
  - [project model](https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/Project.scala#L30) this is where the Github information is stored
  - [github info](https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/misc/GithubInfo.scala#L26)
- [ ] add a search sorting field
  - [html template](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/result.scala.html#L33)
  - [api](https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/DataRepository.scala#L24)
  - [elasticsearch sort by array length](http://stackoverflow.com/a/27883807/449071)

**Comment by jvican** [comment]
Very valuable info, totally for it.
