### ISSUE TITLE
Add a separation by keyword support in the project list view

### ISSUE THREAD

**Issue by 2m** [scalacenter/scaladex#272]
It would be great if the project list could be broken down by keywords. For example a search query [dependencies:akka/*](https://index.scala-lang.org/search?q=dependencies:akka/*) returns all of the projects that build on top of Akka. Having that list broken down by keywords would give a nice overview of Akka Community projects of certain category, like [Akka Persistence Plugin](https://index.scala-lang.org/search?q=keywords:akka-persistence-plugin) or [Akka Extension](https://index.scala-lang.org/search?q=keywords:akka-extension) or any other keyword.

Previous discussion [here](https://github.com/akka/akka/issues/16618#issuecomment-243302282).

**Comment by MasseGuillaume** [comment]
Great idea! It was in the initial design but got lost in translation.

If someone wants to implement this feature here are some pointers:

* [extend aggregation to accept a query](https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/Api.scala#L273)
* [add aggregation result to the search route](https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/Server.scala#L421)
* [render aggregation in search result html template](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/result.scala.html#L18)

**Comment by 2m** [comment]
This is great. Thanks!
