### ISSUE TITLE
Login reports internal server error

### ISSUE THREAD

**Issue by dylemma** [scalacenter/scaladex#273]
When logged in to Github in my usual browser, and I try to log in to scaladex, I get a generic error screen that simply says `There was an internal server error.` If I try from incognito mode, I get the Github login form, but once I complete it, I get back to the same error page.

**Comment by MasseGuillaume** [comment]
Can you [create a github _Personal access tokens_ with read:org permissions](https://github.com/settings/tokens/new) and email it to me at masgui@gmail.com ?

It's most likely a bug in our application logic.

**Comment by dylemma** [comment]
(sent)

**Comment by MasseGuillaume** [comment]
@dylemma I'm redeploying, can you make sure it works in a couple of minutes ?

**Comment by dylemma** [comment]
Sorry for the delay - yes it works! Thanks!
