### ISSUE TITLE
Some libraries not being indexed

### ISSUE THREAD

**Issue by joshlemer** [scalacenter/scaladex#282]
I have a library called [MultiIndex](https://github.com/joshlemer/MultiIndex) which I would like to get indexed on Scaladex. I have published my library to Maven Central [here](http://search.maven.org/#artifactdetails%7Ccom.github.joshlemer%7Cmultiindex_2.11%7C0.1.1%7Cjar), and the library hasn't been indexed for weeks, and I've also tried to use the Scaladex sbt plugin to push my library to Scaladex, but it just yields a `500 Internal Server Error` error:

```
> scaladex:publish
[info] Updating {file:/home/joshu/Dev/MultiIndex/}multiindex...
[info] Wrote /home/joshu/Dev/MultiIndex/target/scala-2.11/multiindex_2.11-0.1.1.pom
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4 ...
[info] Done updating.
[info] :: delivering :: com.github.joshlemer#multiindex_2.11;0.1.1 :: 0.1.1 :: release :: Sat Oct 15 08:18:09 EDT 2016
[info]     delivering ivy file to /home/joshu/Dev/MultiIndex/target/ivy-0.1.1.xml
[trace] Stack trace suppressed: run last scaladex:publish for the full output.
[error] (scaladex:publish) java.io.IOException: PUT operation to URL https://index.scala-lang.org/publish?keywords=Indexes&keywords=Indexing&keywords=Data%20Structure&readme=true&info=true&contributors=true&path=/com/github/joshlemer/multiindex_2.11/0.1.1/multiindex_2.11-0.1.1.pom failed with status code 500: Internal Server Error
[error] Total time: 3 s, completed 15-Oct-2016 8:18:11 AM
```

**Comment by MasseGuillaume** [comment]
@joshlemer thanks for reporting. I'm investigating what went wrong.

**Comment by MasseGuillaume** [comment]
Oh this dates from the 15 of October. The issue was file permissions on the server. I tried out again, this time it does not produce an error but does not index for some reason. Stay tuned.

**Comment by MasseGuillaume** [comment]
@joshlemer I'm currently collaborating with the Sonatype team on this issue (They own maven central). They will push pom files directly to Scaladex when they receive a Scala pom. They are currently testing out our api. Stay tuned.

**Comment by Atry** [comment]
https://github.com/ThoughtWorksInc/sbt-api-mappings, https://github.com/ThoughtWorksInc/sbt-scala-js-map, https://github.com/ThoughtWorksInc/sbt-scala-js-map, https://github.com/Atry/sbt-haxe and https://github.com/Atry/pttrt is also not indexed yet.

**Comment by MasseGuillaume** [comment]
@Atry sbt plugins are not indexed in general see https://github.com/scalacenter/scaladex/issues/191

**Comment by Atry** [comment]
These plugins are not published via Ivy2.
They are hosted on Maven Central as well: https://repo1.maven.org/maven2/com/thoughtworks/sbt-api-mappings/sbt-api-mappings_2.10_0.13/1.0.0/

**Comment by MasseGuillaume** [comment]
@Atry oh ok. Then it's because it was not proxied by Bintray jcenter. Our contribution with Sonatype will solve this issue.

**Comment by julienrf** [comment]
@MasseGuillaume Do we still have this issue? Can you check with people from sonatype that they notify us also when an sbt plugin is released?

**Comment by MasseGuillaume** [comment]
Yeah,

An old release in maven central not proxied on Bintray for example. Over time we will be more in sync with maven central and this issue will be less and less noticeable.

**Comment by MasseGuillaume** [comment]
https://github.com/ThoughtWorksInc/sbt-api-mappings
https://index.scala-lang.org/thoughtworksinc/sbt-api-mappings

https://github.com/ThoughtWorksInc/sbt-scala-js-map
https://index.scala-lang.org/thoughtworksinc/sbt-scala-js-map

https://github.com/Atry/pttrt
https://index.scala-lang.org/atry/pttrt

https://index.scala-lang.org/joshlemer/multiindex

sbt-haxe is not in https://bintray.com/sbt/sbt-plugin-releases this is why it's not indexed.
