### ISSUE TITLE
Display which targets are library supports

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#288]
splitting from #81

- [ ] I would be really nice to see immediately what Scala versions libraries support (e.g., 2.10/2.11/..., Scala.js) + target logos
  - targets in [project](https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/Project.scala#L45) (ex: scala_2.11, scala.js_0.6)

- [ ] improve the front page ui with some target logos

**Comment by SethTisue** [comment]
especially timely right now, with 2.12.0 just released!

**Comment by MasseGuillaume** [comment]
"top priority" ;-)

**Comment by MasseGuillaume** [comment]
![Scala.js logo](https://avatars3.githubusercontent.com/u/6039724?v=3&s=400)
![JVM logo](http://thjug.com/assets/logo.png)

**Comment by vossad01** [comment]
#81 indicated a desire for this information to also appear in the search results.  That request/requirement does not appear here.
