### ISSUE TITLE
Publishing to scaladex not working

### ISSUE THREAD

**Issue by pjan** [scalacenter/scaladex#293]
Been trying to publish to scaladex according to the documentation in github,
but they don't appear on the index. Anything I can do to help you debug this?

(talking about `io.pjan % akka-d3 %% 0.1.0` (pjan/akka-d3 on gh). Has been published on maven.

**Comment by MasseGuillaume** [comment]
@pjan thanks for letting me know. I'm investigating what went wrong.

**Comment by holograph** [comment]
Same in my case, I haven't reported 'cause I'm struggling with a different issue but at least a few publishing attempts ("com.wix" % "accord-core" %% "0.6", specifically with Scala 2.12) had no visible effect.

**Comment by MasseGuillaume** [comment]
Sonatype is now pushing new releases directly to scaladex. You don't need to publish to Scaladex anymore.
