### ISSUE TITLE
Scaladex site not working

### ISSUE THREAD

**Issue by cocevk** [scalacenter/scaladex#295]
Probably not the best place to submit this...

HTTP Request:

https://index.scala-lang.org

Response:

502 Bad Gateway

**Comment by MasseGuillaume** [comment]
@cocevk really sorry I'm redeploying right now. Should not be long.

**Comment by cocevk** [comment]
@MasseGuillaume so no problem if I submitted the bug here?

**Comment by MasseGuillaume** [comment]
@cocevk no problem at all. We just did not had the time to setup a 2nd server to redeploy without interruption. It's something work considering.

**Comment by MasseGuillaume** [comment]
see #296
