### ISSUE TITLE
Index some java artifacts

### ISSUE THREAD

**Issue by jypma** [scalacenter/scaladex#302]
[ts-reaktive](https://github.com/tradeshift/ts-reaktive) is a mixed multi-module Scala/Java SBT project. Some artifacts are Scala, some artifacts are Java-only. It's currently Java-focused, but we expect to add more Scala DSLs.

It's a bit unfortunate that its Java side seems to be ignored on its [Scaladex page](https://index.scala-lang.org/tradeshift/ts-reaktive). Now I realize this is a _Scala_ index, but could e.g. at least the Java artifacts also be made to show in the top-right dropdown? Maybe with a tag or something, that'd be even better.

After all, one of the reasons we started `ts-reaktive` was to show Java folks that writing reactive, immutable code is the way forward, while helping them to stumble onto Scala as well ;-)

**Comment by patriknw** [comment]
This is important for [Akka community page](http://akka.io/community/), which should be able to list java and scala projects.

**Comment by ktoso** [comment]
Another known example of such library (written in Java, because we needed it to not depend on any given scala version) is the widely used https://github.com/typesafehub/config which we'd love to be listed in scalaindex as well. Akka and many many other projects use it as the configuration lib.

Would there be a way to somehow tag such libraries to have them included in scalaindex?

**Comment by MasseGuillaume** [comment]
I will need to tweak things a bit but it should be possible.

We search Bintray for artifact containing the scala binary version in it's path: for example _2.11. Some artifacts don't use this convention and we have this workaround:
https://github.com/scalacenter/scaladex-contrib/blob/master/non-standard.json#L15
we can add for example:  `"com.typesafe config": "java"`

From here we just make the ScalaTarget optional
https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/project/ProjectConvert.scala#L31
https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/Release.scala#L226

In fact, there is not a lot of coupling with Scala in Scaladex. The same code could be used for a Java Index ;-).

**Comment by ktoso** [comment]
I'm not quite clear what are the next steps here?

**Comment by MasseGuillaume** [comment]
Hey @ktoso,

I currently don't have the time to implement this right now. As soon I have some hacking time on Scaladex, I can add this feature. It's about 1 day of implementation time.

Meanwhile, you can add the java projects you wish we index in [non-standard.json](https://github.com/scalacenter/scaladex-contrib/blob/master/non-standard.json#L15)

**Comment by ktoso** [comment]
With the "pom" option? I'm not sure what to put there, are those modes documented somewhere?

**Comment by ktoso** [comment]
I see, it is https://github.com/scalacenter/scaladex-contrib#index-artifacts-which-are-published-in-java-style

Thanks!

**Comment by MasseGuillaume** [comment]
@jypma can you make sure all ts-reaktive are listed here:
https://github.com/scalacenter/scaladex-contrib/pull/18/files#diff-8895eca74dad77edf4c2ea0b82cd983aR17

**Comment by MasseGuillaume** [comment]
@ktoso now live: https://index.scala-lang.org/typesafehub/config

thanks a lot!

**Comment by MasseGuillaume** [comment]
@jypma java projects are now listed https://index.scala-lang.org/tradeshift/ts-reaktive/ts-reaktive-actors

**Comment by jypma** [comment]
Thanks a lot!

**Comment by ktoso** [comment]
Awesome, thanks :)
