### ISSUE TITLE
"relevant" results aren't

### ISSUE THREAD

**Issue by tpolecat** [scalacenter/scaladex#303]
When you search for `database` the "relevant" results are a bunch of noise. Anorm is the top recognizable result at 6, but it's a fork of the real one at 8; doobie is at 10; and Slick is down at 45.

I suggest you turn that option off and default to something like stars which at least has some relationship with reality.

**Comment by MasseGuillaume** [comment]
You can edit your projects to add keywords. I did just that and your project is on the top of the list: https://index.scala-lang.org/search?q=database

**Comment by heathermiller** [comment]
@MasseGuillaume, hang on. Before closing, let's ask @tpolecat if this solution is one that he's satisfied with. 

I think what he's saying is that a bunch of things that aren't really related to databases show up in the search results, so he's suggesting that we think about tweaking how "relevant" results are calculated. This is less about doobie and more about the relevance of the results in general. It indeed might be helpful to take into consideration the # of stars for a given project when calculating relevance.

**Comment by tpolecat** [comment]
Right, thanks @heathermiller. My issue isn't with doobie not being at the top (it shouldn't be, although it should be on the first page) but that Slick is at 45th. In the absence of curation (which is the case for most libraries in Scaladex) it seems like the relevance algorithm doesn't have much to work with and it's giving very misleading results.

So yes, I think it needs to be tweaked until it's giving plausible results and if that's not possible maybe pick something else as the default view.

**Comment by MasseGuillaume** [comment]
It look like slick was tagged with db not database. I'm renaming all db to database.

**Comment by heathermiller** [comment]
@MasseGuillaume, I think I side a bit more with @tpolecat here. While I do agree that people should be a bit more proactive about tagging their libraries, Scaladex can also go a long way by tweaking how the results are calculated. In particular, I think that considering stuff like stars might be a good source of information when ranking relevance. 

Where is relevance determined right now? I've seen this line of code but can't remember where it was. Maybe we can shuffle things around and improve the relevance of the search results by changing this one line of code (I too find that search results are sometimes quite bad...)

**Comment by julienrf** [comment]
Test cases: [scalafix](https://index.scala-lang.org/search?q=scalafix), [doobie](https://index.scala-lang.org/search?q=doobie).

**Comment by tpolecat** [comment]
I renew my call to turn "relevant" off. It doesn't work.

**Comment by olafurpg** [comment]
One more test case that I bumped into when adding a library in scastie

<img width="445" alt="screen shot 2017-03-14 at 11 16 57" src="https://cloud.githubusercontent.com/assets/1408093/23895934/e0e993e0-08a7-11e7-9a39-9290acac1ce2.png">

I think it's better to return the `json` repo for the query "json" if it allows for people to find projects by name. Currently, the top results for scalafmt, scalafix and scalameta all return unrelated projects.

**Comment by MasseGuillaume** [comment]
Let's merge this issue with this one https://github.com/scalacenter/scaladex/issues/389

I added test cases for relevance issues pointed out in this issue: https://github.com/scalacenter/scaladex/issues/389#issuecomment-314463810. I would be really cool if you guys could review the test.
