### ISSUE TITLE
scaladex should be mentioned on scala-lang.org

### ISSUE THREAD

**Issue by tpolecat** [scalacenter/scaladex#304]
I can't find a link to Scaladex from scala-lang.org or scala.epfl.ch … seems like it should be front and center if we want people to use it.

**Comment by heathermiller** [comment]
Yep, good point! Adding this to my list of todos for the next scala-lang update (soon).

**Comment by MasseGuillaume** [comment]
It's a bit hidden: http://scala-lang.org/community/#community-libraries-and-tools

**Comment by MasseGuillaume** [comment]
It will be on the front page soon.

https://github.com/scala/scala-lang/pull/606
preview: https://scala-lang-site.herokuapp.com

**Comment by MasseGuillaume** [comment]
This is now live!
