### ISSUE TITLE
Some artifacts are missing

### ISSUE THREAD

**Issue by intracer** [scalacenter/scaladex#307]
See https://index.scala-lang.org/deanwampler/command-line-arguments, Only 2.10 artifacts are shown

It has 2.11 artifacts: https://mvnrepository.com/artifact/com.concurrentthought.cla/command-line-arguments_2.11 and 0.3.0 version, but Scaladex shows only 2.10 and 0.2.1

**Comment by MasseGuillaume** [comment]
Artifacts for 2.11 are now indexed.

**Comment by intracer** [comment]
ok, it now shows 2.11 artifacts, but not all versions:

There are  6 versions (0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.1, 0.1.0) for 2.11:
https://mvnrepository.com/artifact/com.concurrentthought.cla/command-line-arguments_2.11

And only 2 versions (0.4.0 and 0.2.1) for 2.10
https://mvnrepository.com/artifact/com.concurrentthought.cla/command-line-arguments_2.10

And Scaladex shows for 2.11 only the two versions (0.4.0 and 0.2.1) that have 2.10 artifacts too.

**Comment by MasseGuillaume** [comment]
You are right. We are still missing some release. 

We have two way of indexing: search on Bintray and get new releases from Sonatype (Maven Central). Bintray has a repository called JCenter, it's almost a proxy of Maven Central. We will only see in the search a release that was proxied to a user.

**Comment by intracer** [comment]
Should we open an issue to track that?

**Comment by MasseGuillaume** [comment]
Let me ask Sonatype if they can give send a batch update of previous releases.

**Comment by MasseGuillaume** [comment]
It's not possible to have the older releases.
