### ISSUE TITLE
Pressing "Back" after changing the "Artifact" does not restore the previous "Artifact"

### ISSUE THREAD

**Issue by vossad01** [scalacenter/scaladex#313]
Steps to reproduce:
 1. Got to https://index.scala-lang.org/akka/akka/akka-actor
 2. Choose "akka-camel" from the artifact selection box.
 3. Note that Statistics, Dependencies, and Dependents change
 4. Press Back
 5. Notice that Statistics, Dependencies, and Dependents change back but the artifact selection box still says "akka-camel."  The page is now in a state of presenting false information.

**Comment by MasseGuillaume** [comment]
It look like a bug in bootstrap-select: https://github.com/silviomoreto/bootstrap-select/issues/1023
