### ISSUE TITLE
akka-http-session presents stale or incomplete version information

### ISSUE THREAD

**Issue by adamvoss** [scalacenter/scaladex#333]
[The Scaladex page for softwaremill/akka-http-session](https://scaladex.scala-lang.org/softwaremill/akka-http-session) lists only one artifact version and it targets 2.10.

Reading the projects README, it is clear that there are newer versions.

[The newer versions show up on sonatype](https://oss.sonatype.org/#nexus-search;quick~akka-http-session).  I note that the Scaladex page lists adding a bintray resolver in the installation section.  So it seems perhaps Scaladex is looking in the wrong place (or not aggregating results)?

I think I have noticed this with other packages as well, this is the first time I took note of a specific example to be able give a detailed report.

**Comment by MasseGuillaume** [comment]
I changed the default artifact to core. The information is now correct.
