### ISSUE TITLE
Results in search box are duplicated

### ISSUE THREAD

**Issue by jvican** [scalacenter/scaladex#335]
For some reason, I've started to experience this behaviour in Scaladex. It's weird because it was not happening before. Have a look at the following image:

![scaladex-issue png](https://cloud.githubusercontent.com/assets/2462974/21848962/9bf416a4-d803-11e6-8b43-a0e30b325846.png)

Search results are duplicated and I cannot browse them until the end, the cursor only allows me to go until the first ammonite-v1 (which should be the correct thing to do if only the first n would be shown, not 2*n). Thanks for the great work in Scaladex!

**Comment by vossad01** [comment]
`git bisect` points to this being introduced by de97136b81dc34ca7b369c3a4db5819c4c8b7d66

I may be wrong about that because I encountered some issues at first with unexpected caching switching between versions, but once I accounted for that it seemed to be the commit mentioned above.

**Comment by MasseGuillaume** [comment]
it look like this was fixed
