### ISSUE TITLE
Slow Refresh of Version

### ISSUE THREAD

**Issue by darkfrog26** [scalacenter/scaladex#336]
On the right side of the page the version is very often far out of date.  I know that crawling is expensive, but this makes Scaladex far less useful as I have to double-check the versions stated before I actually use anything I find there.

One option for improvement might be to write some custom JavaScript (Scala.js of course) that uses the browser to validate the current version in the browser.  If the version is out-of-date it could update it dynamically as well as notify the server that it needs to be re-crawled thus increasing the rate at which out-of-date items are refreshed without having to crawl absolutely every project.

**Comment by MasseGuillaume** [comment]
Can you give me examples of libraries not up to date.

**Comment by darkfrog26** [comment]
https://scaladex.scala-lang.org/outr/scribe

You can see maven-central says 1.3.2 but on the side the version is 1.2.6 and in the badge.

**Comment by vossad01** [comment]
Conceptually, #333 presents the same problem.  Investigation would be needed to show if it represents a different root cause.

**Comment by darkfrog26** [comment]
I think it is likely the same bug.

**Comment by MasseGuillaume** [comment]
duplicate #333
