### ISSUE TITLE
keywords are not persisted properly

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#337]

**Comment by julienrf** [comment]
I checked that the issue was closed by doing the following steps:
- I deployed scaladex ;
- I changed the keywords of some project ;
- I redeployed scaladex ;
- I checked that the keywords were still present.

**Comment by MasseGuillaume** [comment]
Thanks @julienrf !

**Comment by julienrf** [comment]
I think ElasticSearch and the scaladex-index repos are out of sync sometimes, which has the same effect as loosing keywords.

**Comment by julienrf** [comment]
We see that the keyword “spark” is set for the apache/spark project:

~~~
$ grep -A 10 "apache/spark" scaladex-index/live/projects.json 
  "apache/spark":{
    "contributorsWanted":false,
    "keywords":[
      "spark"
    ],
    "defaultArtifact":"spark-core",
    "defaultStableVersion":true,
    "deprecated":false,
    "artifactDeprecations":[
      
    ],
~~~

However:

![image](https://cloud.githubusercontent.com/assets/332812/23659221/b3e5e540-0345-11e7-96ed-7ff623bf4166.png)

So, clearly, Elastic Search “forgot” about this keyword in some way, though it is still in our index.

**Comment by MasseGuillaume** [comment]
I moved the reindexing in the redeploy task. It's now indexing with the scaladex user and using the index folder in its home directory.

I think that was causing the issue.
