### ISSUE TITLE
Macwire mixed with Clippy

### ISSUE THREAD

**Issue by adamw** [scalacenter/scaladex#339]
On MacWire's page: 

https://scaladex.scala-lang.org/adamw/macwire

the RHS shows artifacts of softwaremill/clippy. Clippy itself isn't in the index at all.

**Comment by vossad01** [comment]
To clarify, the installation instructions on the adamw/macwire/plugin artifact gives the following installation instructions:

> "com.softwaremill.clippy" %% "plugin" % "0.4.0"

While the expected would be the following artifacts under "com.softwaremill.macwire":

 - core
 - macros
 - proxy
 - runtime
 - scopes
 - util


"softwaremill/scala-clippy" has specified incorrectly specified its `scm` to be the MacWire GitHub repository so the artifact for clippy is appearing under the "adamw/macwire/" project on Scaladex.

Source of issue can be seen here: https://github.com/softwaremill/scala-clippy/blob/master/build.sbt#L52

**Comment by MasseGuillaume** [comment]
@vossad01 correctly identified the problem.

You can override the bogus scm tag via a PR in https://github.com/scalacenter/scaladex-contrib/blob/master/claims.json#L870
"com.softwaremill.clippy *": "softwaremill/scala-clippy"

I'm investigating why macwire is not in the index.
It's available on maven central: http://search.maven.org/#artifactdetails%7Ccom.softwaremill.macwire%7Cutil_2.12%7C2.2.5%7Cjar

**Comment by adamw** [comment]
Ah! Thanks for noticing that, a copy-paste error :) Didn't know this info is actually used anywhere ;)

I just pushed a change in clippy's build.sbt, should I do something on scaladex to fix the listings?

**Comment by MasseGuillaume** [comment]
@adamw yep check first paragraph of above comment

**Comment by adamw** [comment]
@MasseGuillaume ah sorry I somehow missed that :) I suspect this override is needed despite a fix in the source because of old released versions?

**Comment by adamw** [comment]
Here's the PR, thanks for the help :)
https://github.com/scalacenter/scaladex-contrib/pull/19
