### ISSUE TITLE
Is it possible to get download counts for Scaladex?

### ISSUE THREAD

**Issue by adamvoss** [scalacenter/scaladex#349]
Currently Scaladex has two data sources which allow for the download of artifacts: Bintray and Sonatype.

[Sonatype](http://oss.sonatype.org/) does not have any publicly accessible download statistics available.  According to the documentation, it seems only the owner of a package can get the statistics for it.  Therefore, unless Sonatype does something special for Scaladex, we cannot get statistics for those packages.

Bintray does make download statistics available.  However, only in a limited fashion, the actual download numbers may not be made public, or some repositories may not provide data beyond the last 30 days.

The very unscientific check of looking at the sizes of the `maven-central` and `bintray` directories in the Scaladex index, shows Bintray 590 MB vs Maven-Central 43 MB suggesting there are significantly more artifacts using Bintray.

Even if we have to put disclaimers on the website about exclusions and not all packages having statistics, I still think collecting this data so that having download count information could be displayed on artifacts where we have it and eventually aggregate statistics be made available on the site would be a boon for users.  With enough penetration this could potentially be good data point in refining search (#303).

The short answer is there really does not seem to be a way to accomplish this at this time, but I wanted to put this out there in case someone sees a way to achieve this that I am missing and so there is will have been some record of demand for this.

**Comment by MasseGuillaume** [comment]
I spoke with Sonatype and they do no want to share this information.
