### ISSUE TITLE
Should a user be able to choose which repository they want to download from?

### ISSUE THREAD

**Issue by adamvoss** [scalacenter/scaladex#350]
In the event the same artifact is published on Sonatype and Bintray, should this be in anyway reveled to the user?  Should they then be given the choice on where they want to install it from or is it acceptable for Scaladex to make the decision for them?

This would have implications for #349, on the outside chance any repository did ever provide download statistics.
#333 provides and example of an artifact that can be found in both places.

(This is an isolated question concerning what and how things can be uniquely identified in Scaladex.  The general question was quite long I am working to split it up.)

**Comment by MasseGuillaume** [comment]
In sbt Sonatype is available by default and Bintray is not, this is why we can favor Sonatype.

**Comment by MasseGuillaume** [comment]
This is a rare case. I'm closing this without a solution.
