### ISSUE TITLE
Does routing support Scaladex supporting SCM provideres other than GitHub?

### ISSUE THREAD

**Issue by adamvoss** [scalacenter/scaladex#351]
I this issue hopes address whether the current routing scheme has adequate support support alternatives to GitHub if desired later.  I am not meaning to advocate support for other platforms, but this question was relevant to a broader question of what and how things can be uniquely identified in Scaladex so I thought to raise it.  

**tl;dr** so long as the bolded constraints shown below seem acceptable, supporting other GitHub-like SCM providers does not seem to necessitate any routing changes.  If there are issues with the constraints, and there is a desire to leave the option to supporting additional SCM providers open, it may be worthwhile determining a url scheme now to reduce the potential breaking changes in the future.  The main issue besides the below would be with projects moving between SCM providers, but that is best discussed in the context of #95)

___

Right now, the addressable route for an artifact takes the form:
 > `$organization/$project/$artifact/$version`

With the information sources as follows:

```
 organization <- Github User or Github Organization (unique on Github)
 project <- Github Repository (unique within Github user/repository)
 artifact <- Sourced from pom (unique within repository and `groupId`)
 version <- Sourced from pom (unique within repository, `groupId`, and `artifactId`)
```

As can be seen there nothing enforcing uniqueness constraints between the first half and the last half so there would be potential for conflict.  It is probably not unreasonable for Scaladex to enforce that **artifacts of the same name but different `groupId` must not be produced from the same repository**.  Doing so would be confusing.  While it is technically feasible to create this situation it would need to be recognized that Scaladex imposes additional constraints and such situations will not be supported.

If we hypothetically introduce support beyond Github, the above would likely become:

```
 organization <- User or Organization (unique across Github)
 project <- Repository (unique within organization)
 artifact <- Sourced from pom (unique within repository and `groupId`)
 version <- Sourced from pom (unique within repository, `groupId`, and `artifactId`)
```

Again there is nothing external to enforce the uniqueness across systems.  However, I cannot think of a legitimate (NB. #178) case where uniqueness would not be preserved.  Therefore, Scaladex could constrain that **an artifact having the same name (artifactId) under the same named User and Repository at two different SCM providers must have the same `groupId`**.

**Comment by MasseGuillaume** [comment]
At the time I tested >95% poms was using github in its scm tag.
