### ISSUE TITLE
Aggregate information all like-named releases on artifact page

### ISSUE THREAD

**Issue by adamvoss** [scalacenter/scaladex#354]
A versioned artifact as shown on the artifact page, actually consists of multiple releases; one for each target version of Scala.  However, the right-hand side of the UI only displays information pertaining one of the releases for the currently selected version.  The user has no control to specify which Scala target they see nor may they realize there is data not being presented.

I propose aggregating the information from all releases of a versioned artifact on the existing artifact page.  This would solve the problem of "lost" data while keeping the UI simple buy not revealing the choice between different releases to user.

This issue is effectively resultant from #325 and was noticed again by #314.

**Comment by MasseGuillaume** [comment]
Here you go: https://index.scala-lang.org/artifacts/scalaz/scalaz
