### ISSUE TITLE
Responsive layout for page heading does not work well when logged in

### ISSUE THREAD

**Issue by adamvoss** [scalacenter/scaladex#356]
When not logged in, the site is maybe a little eager to get you to log-in but otherwise fine:
![image](https://cloud.githubusercontent.com/assets/965439/21966061/fe1272be-db31-11e6-8edf-60cadbd10ea3.png)

However, when you do log in things don't layout quite right in responsive mode:
![image](https://cloud.githubusercontent.com/assets/965439/21966051/d61c1508-db31-11e6-905d-b2a9099ebff5.png)

**Comment by jvican** [comment]
Fixing this issue would require some css changes in this file: https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/main.scala.html#L76.
  
A web developer with some styling skills could helps us tackle this one by aligning the menu layout in the responsive mode. This probably requires fiddling with per-resolution css rules.
