### ISSUE TITLE
index.scala-lang now rewritten to scaladex.scala-lang

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#357]
Why was this change made? It's confusing–everywhere I had published that the _package index_ was `index.scala-lang.org`. Now the URL has changed. Why was this necessary?

**Comment by heathermiller** [comment]
E.g., even on this repo's info page...
<img width="441" alt="screen shot 2017-01-16 at 9 19 50 am" src="https://cloud.githubusercontent.com/assets/687163/21975440/fc4eac68-dbcc-11e6-8131-b9dc86728553.png">

Can we please go back to being able to use index.scala-lang.org?

**Comment by MasseGuillaume** [comment]
Let's only use https://scaladex.scala-lang.org now.

**Comment by heathermiller** [comment]
I really don't agree with this being closed. In our talks, blog articles, etc, we refer to index.scala-lang.org. Could you explain why this change was necessary?

**Comment by julienrf** [comment]
My 2 cents: I also prefer keeping using `index.scala-lang.org`.

**Comment by MasseGuillaume** [comment]
hehe ok sent an email to fabien
