### ISSUE TITLE
Cannot change the Default Artifact of a project

### ISSUE THREAD

**Issue by sjrd** [scalacenter/scaladex#366]
The [Scala.js](https://scaladex.scala-lang.org/scala-js/scala-js) defaults to the `scalajs-cli` artifact, which is kind of absurd, because virtually no one uses that. The logical default artifact should be `scalajs-library`.

I tried changing that in the Edit view of the project (which I have access to). But despite changing the artifact in the relevant drop box, after clicking Update, the default artifact is still `scalajs-cli`. If I go back to the Edit view, sure enough, the drop box shows `scalajs-cli` anew.

**Comment by MasseGuillaume** [comment]
fun fact: `false < true`

**Comment by MasseGuillaume** [comment]
https://index.scala-lang.org/scala-js/scala-js
