### ISSUE TITLE
Mac Cmd symbol

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scaladex#367]
<img width="574" alt="screen shot 2017-01-24 at 10 14 22" src="https://cloud.githubusercontent.com/assets/1408093/22241067/178fbf42-e21e-11e6-82a7-0acc9e0dbc9b.png">

**Comment by MasseGuillaume** [comment]
https://github.com/scalacenter/scastie ;-)

**Comment by olafurpg** [comment]
Whoops wrong project
