### ISSUE TITLE
Merge GitHub topics with Scaladex keywords

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#380]
Would be nice if we could fetch the "topics" of a GitHub repository and then merge that with the Scaladex keywords. It'd probably improve search relevance... More data FTW 🙂

**Comment by MasseGuillaume** [comment]
Yeah good idea.
It's not part of the Github API yet. I contacted them and they said:

> Hey Guillaume.
> No, not yet, but the team is working on adding support for topics in the API. Follow the blog for updates:
> https://developer.github.com/changes/
> Thanks for expressing interest in this!
> Best,
> Ivan

**Comment by heathermiller** [comment]
Aww 😢
Guess this goes on the backburner then.

**Comment by MasseGuillaume** [comment]
Now available: https://developer.github.com/v4/reference/object/repositorytopic/

**Comment by heathermiller** [comment]
Finally! 😃
