### ISSUE TITLE
Login link / page doesn't work in all cases

### ISSUE THREAD

**Issue by jrudolph** [scalacenter/scaladex#382]
It seems the login resource at https://index.scala-lang.org/login only sometimes manages to do the redirect to github. In other cases, it will interpret the URL as a search as shown here:

![screenshot from 2017-02-07 09 53 56](https://cloud.githubusercontent.com/assets/9868/22684168/714f7e0e-ecd8-11e6-9103-f9c22f86cc46.png)

I tried with different browsers. With firefox and chrome clicking on the button seems to work mostly but visiting the link directly does never. On my default chromium (which also has lots of plugins which might interfere) clicking the button doesn't work as well.

**Comment by MasseGuillaume** [comment]
Hum

When you [concat](https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/Server.scala#L66) routes are they match from top to bottom? The OAuth2 routes is responsible for the login.

**Comment by jrudolph** [comment]
Yes, they match from top to bottom basically. The problem might also be that in https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/routes/Oauth2.scala#L23 the referer header is *required* to make the redirect. It might make sense to make that one optional and use a default target (e.g. the homepage) for the github request `state`.
