### ISSUE TITLE
Scala libraries shown as java dependency and inconsistent dependents list

### ISSUE THREAD

**Issue by intracer** [scalacenter/scaladex#387]
https://index.scala-lang.org/strongtyped/active-slick shows 

4 Dependencies
scala/scala-library v2.11.6 compile
Java Dependencies
com.typesafe.slick/slick_2.11 v3.1.0 compile
com.h2database/h2 v1.4.181 test
org.scalatest/scalatest_2.11 v2.2.4 test

slick and scalatest are shown as Java Dependencies
if you look for libraries that build upon slick 
https://index.scala-lang.org/slick/slick
it shows 19 Dependents and no active-slick

But there are more in search when you click the link and now active-slick is included
https://index.scala-lang.org/search?q=depends-on:slick/slick&page=2

**Comment by MasseGuillaume** [comment]
@intracer Thanks for reporting this issue!

It look like slick 3.1.0 is not indexed: https://index.scala-lang.org/slick/slick/slick?target=_2.11
What we see in https://index.scala-lang.org/slick/slick are forks (see #178)

**Comment by MasseGuillaume** [comment]
looks good now
