### ISSUE TITLE
Query "scalafmt" results in "scalafx"

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scaladex#393]
See https://index.scala-lang.org/search?q=scalafmt

<img width="1212" alt="screen shot 2017-03-01 at 14 22 16" src="https://cloud.githubusercontent.com/assets/1408093/23461505/820caa14-fe8a-11e6-865f-e8b19535772c.png">

I expected scalafmt to be at the top of the search list, esp. since scalafmt 

- is tagged with the "scalafmt" keyword
- has more stars
- has more contributors

**Comment by olafurpg** [comment]
These search results leak into scastie making it hard to add a dependency on scalafmt or scalafix

<img width="611" alt="screen shot 2017-03-01 at 13 33 45" src="https://cloud.githubusercontent.com/assets/1408093/23461541/a370cda2-fe8a-11e6-956c-239f5ce3a853.png">
<img width="628" alt="screen shot 2017-03-01 at 13 33 53" src="https://cloud.githubusercontent.com/assets/1408093/23461563/b794d83c-fe8a-11e6-89d0-66113d6efd13.png">

**Comment by julienrf** [comment]
Related: #303
