### ISSUE TITLE
Pagination performs too many requests

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scaladex#396]
At [this place](https://github.com/scalacenter/scaladex/blob/0ee4cc28567ba69426780d44881008e16a99036f/data/src/main/scala/ch.epfl.scala.index.data/bintray/BintrayListPoms.scala#L99-L100) we compute the number of pages to load. However, `X-RangeLimit-Total` gives the number of results, not the number of pages. Hence, we perform way too many calls.

Eventually we want to use [BintrayClient.fetchPaginatedResource](https://github.com/scalacenter/scaladex/blob/91f0c0cd4d840e1cc7ea855675fe1a83c0ed653e/data/src/main/scala/ch.epfl.scala.index.data/bintray/BintrayClient.scala#L66) instead, which makes just the required number of calls, not more :)

**Comment by jvican** [comment]
This would probably require to change an API call, which would be quite easy! This would make the website faster on load times, which is important for UX. @julienrf can probably elaborate on this when this ticket is unblocked.

**Comment by MasseGuillaume** [comment]
@jvican this is when we index not when we load a page.
