### ISSUE TITLE
add scalafmt

### ISSUE THREAD

**Issue by cvogt** [scalacenter/scaladex#397]
we are talking to it as a library from sbt and cbt, so it sounds like it should be in scaladex

**Comment by heathermiller** [comment]
It's in there: https://index.scala-lang.org/olafurpg/scalafmt

If you searched for it and couldn't find it, seems like this is related to #389

**Comment by heathermiller** [comment]
Closing. Reopen if I somehow misunderstood this ticket! :)

**Comment by MasseGuillaume** [comment]
@heathermiller thanks!

**Comment by cvogt** [comment]
@heathermiller can confirm. moved discussion to #389 thx!
