### ISSUE TITLE
Invalid targets shown on project pages causing 404

### ISSUE THREAD

**Issue by travis032654** [scalacenter/scaladex#400]
https://index.scala-lang.org/playframework/playframework/play?target=_sjs0.6_2.11

**Comment by julienrf** [comment]
This one is similar to the other one: as long as there is no selected artifact you should not add it to the hidden input next to the target dropdown.

**Comment by julienrf** [comment]
Selecting this target should lead to the following page: https://index.scala-lang.org/playframework/playframework?target=_sjs0.6_2.11
