### ISSUE TITLE
Cats scaladoc link returns AccessDenied error

### ISSUE THREAD

**Issue by gerferra** [scalacenter/scaladex#404]
The scaladoc link on [typelevel/cats](https://index.scala-lang.org/typelevel/cats) links to https://www.javadoc.io/doc/org.typelevel/cats_2.12/0.9.0 which is returning an AccessDenied error:
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>0AA83E8D7B25F886</RequestId>
  <HostId>2NL6ziwPUCqhFfyBgUxrNp74/Bliv865ye/3sM/5fBf0H/K1LS1LkTcGm7dN5ASVXvL37Wzc4ow=</HostId>
</Error>
```
The scaladoc link on the cats website is working fine: http://typelevel.org/cats/api/

**Comment by MasseGuillaume** [comment]
It look like this artifact does not publish javadoc but cats-core does.

https://www.javadoc.io/doc/org.typelevel/cats-core_2.12/0.9.0

**Comment by gerferra** [comment]
Now the scaladoc link directs to the cats-core artifact. So this is fixed up. Thanks :smile:
