### ISSUE TITLE
Shows artifact information from another repository

### ISSUE THREAD

**Issue by raboof** [scalacenter/scaladex#405]
For example on https://index.scala-lang.org/scalapenos/stamina , the README shown is indeed the stamina readme, but the 'right side' of the screen defaults to showing the 'cakemix' artifact (which is in a different repository under the same organization).

I think I'd expect https://index.scala-lang.org/scalapenos/stamina to show the same as https://index.scala-lang.org/scalapenos/stamina/stamina

**Comment by MasseGuillaume** [comment]
This is a typo in cakemix POM.
https://repo1.maven.org/maven2/com/xebia/cakemix_2.12/1.0.0/cakemix_2.12-1.0.0.pom

fixed in: https://github.com/scalacenter/scaladex-contrib/commit/32ce49390a7f6dde4a9f53a6ca18b664e9ccb90a

**Comment by raboof** [comment]
Aha I didn't expect that information to come from there. Isn't that kind of dangerous?

Proposed the fix upstream, also (https://github.com/xebia/cakemix/pull/12/files)

**Comment by MasseGuillaume** [comment]
yep https://github.com/scalacenter/scaladex/issues/178

we should blacklist eveything and make shure developpers claim their repository.
