### ISSUE TITLE
FAQ: example sbt code for resolving through jCenter

### ISSUE THREAD

**Issue by raboof** [scalacenter/scaladex#406]
The FAQ at https://github.com/scalacenter/scaladex/wiki/FAQ shows `resolvers := Resolver.jcenterRepo`, that should be `resolvers := Seq(Resolver.jcenterRepo)`

Even then I'm not sure this works at all - it seemed to download through `repo1.maven.org` anyway the first time and then not download at all (as the resource was already cached)... perhaps we can recommend a better way?

**Comment by MasseGuillaume** [comment]
We now have updates directly from maven central. Only older artifact will need to use this method. Another way to do it would be to access the url in JCenter directly. (via a web browser for example)

**Comment by MasseGuillaume** [comment]
I removed the jcenter bit from the FAQ. We are now receiving new releases directly from Sonatype. This should not be a problem anymore.
