### ISSUE TITLE
What links to use for 2.13 libraries list?

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scaladex#411]
none of the following links seem to work. these are based off 2.12 URLs that once worked. what URLs should I be using now? this is for use at https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md

### Scaladex

Scaladex, the index of Scala libraries, now offers searching by target version:

* [Scala modules for 2.13.0-M1](https://index.scala-lang.org/search?q=targets%3Ascala_2.13.0-M1+AND+keywords:scala-module)
* [Testing frameworks for 2.13.0-M1](https://index.scala-lang.org/search?q=targets%3Ascala_2.13.0-M1+AND+keywords%3Atesting)
* [Other libraries for 2.13.0-M1](https://index.scala-lang.org/search?q=targets%3Ascala_2.13.0-M1)
* [Compiler plugins for 2.13.0-M1](https://index.scala-lang.org/search?q=keywords%3Acompiler-plugin+AND+targets%3Ascala_2.13.0-M1)
* [Sbt plugins for 2.13.0-M1](https://index.scala-lang.org/search?q=keywords%3Asbt-plugin+AND+targets%3Ascala_2.13.0-M1)

**Comment by xuwei-k** [comment]
https://index.scala-lang.org/search?scalaVersions=2.13 ?

**Comment by MasseGuillaume** [comment]
Correct ^

**Comment by SethTisue** [comment]
@MasseGuillaume will that return libraries published for _any_ Scala 2.13 milestone, or for _only the latest milestone_? it'll start to matter as soon as 2.13.0-M2 exists, since milestones aren't binary compatible with each other

**Comment by MasseGuillaume** [comment]
It will be all 2.13 artifacts.

**Comment by SethTisue** [comment]
ok, that's really not going to be useful at all for very much longer. can we reopen this?

**Comment by SethTisue** [comment]
also, this link doesn't find anything, is the link wrong somehow? https://index.scala-lang.org/search?scalaVersions=2.13&keywords=scala-module

I'm trying to replace all of the following with working links that are M1 specific:

 * [Scala modules for 2.13.0-M1](https://index.scala-lang.org/search?q=targets%3Ascala_2.13.0-M1+AND+keywords:scala-module)
 * [Testing frameworks for 2.13.0-M1](https://index.scala-lang.org/search?q=targets%3Ascala_2.13.0-M1+AND+keywords%3Atesting)
 * [Other libraries for 2.13.0-M1](https://index.scala-lang.org/search?q=targets%3Ascala_2.13.0-M1)
 * [Compiler plugins for 2.13.0-M1](https://index.scala-lang.org/search?q=keywords%3Acompiler-plugin+AND+targets%3Ascala_2.13.0-M1)
 * [Sbt plugins for 2.13.0-M1](https://index.scala-lang.org/search?q=keywords%3Asbt-plugin+AND+targets%3Ascala_2.13.0-M1)

and I don't know how to do it.

**Comment by MasseGuillaume** [comment]
It look like the tag scala-module does not exists.

maybe: https://index.scala-lang.org/scala

**Comment by SethTisue** [comment]
> maybe: https://index.scala-lang.org/scala

how would I combine that with search by target Scala version?

**Comment by MasseGuillaume** [comment]
https://index.scala-lang.org/search?scalaVersions=2.13&q=*+AND+organization%3Ascala&page=1

**Comment by SethTisue** [comment]
> https://index.scala-lang.org/search?scalaVersions=2.13&q=*+AND+organization%3Ascala&page=1

that sort of works but not really... the scala modules appear at the top, but then there's ton of irrelevant search results that follow

**Comment by SethTisue** [comment]
@MasseGuillaume ping? on the one hand, it's not super urgent, but on the other, it would be really useful to me and to the community if we could straighten this out early in the 2.13 cycle

**Comment by MasseGuillaume** [comment]
I think this is the link you want: https://index.scala-lang.org/search?q=organization%3Ascala+AND+scalaVersions%3D2.13

then on each project page the target dropdown (top right) shows the binary version supported

https://index.scala-lang.org/scala/scala-parser-combinators

**Comment by lrytz** [comment]
@MasseGuillaume once 2.13.0-M2 is available there's not way to narrow the search to specific milestone or RC. The 2.13 binary version only starts once the final 2.13.0 is released, pre-releases are all binary incompatible.

**Comment by MasseGuillaume** [comment]
I understand the binary incompatibility.

What, I am saying above is that you can narrow down projects release for 2.13.X then look in each individual project for the target (where I correctly filter by binary version).

For example:
from https://index.scala-lang.org/search?q=organization%3Ascala+AND+scalaVersions%3D2.13
you can identify scala-parser-combinators
and we can see from https://index.scala-lang.org/scala/scala-parser-combinators that only 2.13.0-M1 is available.
(it appears to be correct https://github.com/scala/scala-parser-combinators/blob/1.0.x/build.sbt#L6)

**Comment by SethTisue** [comment]
I'm afraid that's really not very useful at all. it would be _hugely_ more useful if I could search for a specific milestone. is that not, or could not that be, supported?

**Comment by MasseGuillaume** [comment]
Yeah, we can add this. Is the goal to track the latest scala version adoption?

**Comment by SethTisue** [comment]
The primary  goal is to find out what libraries are available for a particular Scala pre-release, with what version number. This will be helpful to library and application authors wanting to try a pre-release. Adoption of the pre-releases is often slow and I think one reason for that is just that it's really tedious to find out what libraries are available and what version numbers to use in order to get them. Scaladex could substantially ease that pain.

**Comment by MasseGuillaume** [comment]
This is an issue for Scastie as well. We search for 2.13.0-M1 and get no results.

https://index.scala-lang.org/api/search?q=collection-strawman&target=JVM&scalaVersion=2.13.0-M1
vs
https://index.scala-lang.org/api/search?q=collection-strawman&target=JVM&scalaVersion=2.13

**Comment by SethTisue** [comment]
@MasseGuillaume this is still on your radar, I hope...?

**Comment by MasseGuillaume** [comment]
@SethTisue I cant do this immediately, I added a bookmark, I will do it as soon as I have time.

**Comment by MasseGuillaume** [comment]
@SethTisue here you go, I'm deploying now.

**Comment by MasseGuillaume** [comment]
https://index.scala-lang.org/search?q=fullScalaVersion%3A2.13.0-M1+AND+NOT+fullScalaVersion%3A2.13.0-M2&scalaVersions=2.13

hehe !

**Comment by SethTisue** [comment]
@MasseGuillaume thank you so much! this is now used in scala/make-release-notes@e2ef4dd575cf6da7b9aceb57e382b059bb4beeef  🎉
