### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by raboof** [scalacenter/scaladex#412]
scaladex saw version 10.0.5+20170317-1706 of akka-http-core on bintray (https://index.scala-lang.org/akka/akka-http/akka-http-core/10.0.5+20170317-1706), but that version was subsequently removed (https://dl.bintray.com/akka/maven/com/typesafe/akka/akka-http-core_2.11/).

Does it go away from scaladex automatically?

**Comment by MasseGuillaume** [comment]
I don't know why Bintray allows you to remove releases but I think It's a bad idea. I prefer to leave them there.

**Comment by raboof** [comment]
Hmm I suppose that makes sense - unfortunately in this case that was an 'accidental' push ;).
