### ISSUE TITLE
Invalid navigation paths presented in drop down selectors

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scaladex#413]
For example when I search for enumeratum I am brought to the enumeratum entry with scala 2.12 selected.  If I switch to enumeratum-play I see 1.5.13 available (but it is not) and end up at a NotFound page: https://index.scala-lang.org/lloydmeta/enumeratum/enumeratum-argonaut/1.5.13

The only way to get the correct selection seems to be to switch scala major versions away and back to 2.12, for example if I select scala 2.11, then back to 2.12 the selections are properly filtered.

**Comment by MasseGuillaume** [comment]
Another way to reproduce it:
go to typelevel/cats
select cats-js
