### ISSUE TITLE
Broken links for a project's website

### ISSUE THREAD

**Issue by MichaelViveros** [scalacenter/scaladex#418]
Some of the Website links on a project's page are broken, they lead to a Not Found page.

Ex. Clicking Website link in https://index.scala-lang.org/scalamolecule/molecule leads to https://index.scala-lang.org/scalamolecule/scalamolecule.org
<img width="806" alt="screen shot 2017-06-03 at 4 31 15 pm" src="https://cloud.githubusercontent.com/assets/8866443/26756889/25b9689e-487a-11e7-842c-5386b77564d2.png">

Narrowed it down to projects whose homepage stored in github aren't valid URLs (with `http://www.` in front)

`./scalamolecule/molecule/repo.json:  "homepage":"scalamolecule.org",
./scala/pickling/repo.json:  "homepage":"lampwww.epfl.ch/~hmiller/pickling",
./dlwh/breeze/repo.json:  "homepage":"www.scalanlp.org",`

Unix command to find these projects:
`find . -name repo.json | xargs egrep -L '"homepage":(null|""|"http.*")' | xargs grep homepage`

**Comment by MasseGuillaume** [comment]
Duplicates #413

**Comment by MichaelViveros** [comment]
This still isn't working:
* Website link for https://index.scala-lang.org/scala/pickling/scala-pickling/0.11.0-M2?target=_2.11 redirects to https://index.scala-lang.org/scala/pickling/scala-pickling/lampwww.epfl.ch/~hmiller/pickling
* Website link for https://index.scala-lang.org/scalamolecule/molecule/molecule/0.12.2?target=_2.12 redirects to https://index.scala-lang.org/scalamolecule/molecule/molecule/scalamolecule.org

**Comment by MasseGuillaume** [comment]
it look like I forgot to deploy it.
