### ISSUE TITLE
Bug: Latest version incorrectly reported for Monix

### ISSUE THREAD

**Issue by alexandru** [scalacenter/scaladex#419]
See: 

- https://index.scala-lang.org/monix/monix/monix
- https://index.scala-lang.org/monix/monix/monix/latest.svg

Values: 

- reported: `2.1.2`
- expected: `2.3.0`

NOTE: this is the main project and the delivered artefact is the POM itself (with no JARs). Maybe this is the issue.

**Comment by MasseGuillaume** [comment]
The monix jvm artifact 2.3.0 is missing from Scaladex.

http://search.maven.org/#artifactdetails%7Cio.monix%7Cmonix_2.12%7C2.3.0%7Cpom

**Comment by MasseGuillaume** [comment]
hum it look like jvm releases are not indexed for the monix artifact. Since 2.1.2

**Comment by MasseGuillaume** [comment]
It looks like what you said above is correct. If we compare

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.monix%22%20AND%20a%3A%22monix_2.12%22
https://index.scala-lang.org/artifacts/monix/monix

we see there is no release in scaladex when the jar is missing

for scalajs there jar is present on both scaladex and maven search
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.monix%22%20AND%20a%3A%22monix_sjs0.6_2.12%22

Sonatype is forwarding us the information. I will let them know we are having this issue.

**Comment by alexandru** [comment]
@MasseGuillaume what happened since 2.1.2 is that main package (io.monix %% monix) has switched to `<packaging>pom<packaging>`, no longer delivering a JAR file, because it would be empty and cause problems with Android AFAIK.

In other words I don't think it is Sonatype to blame. In case Scaladex expects a JAR, then it shouldn't do that.

**Comment by MasseGuillaume** [comment]
ohh I think I found the issue: https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/project/ProjectConvert.scala#L107

Thanks for pointing the packaging.
