### ISSUE TITLE
Scala dependencies are shown as "Java Dependencies"

### ISSUE THREAD

**Issue by Atry** [scalacenter/scaladex#425]
https://index.scala-lang.org/thoughtworksinc/deeplearning.scala/plugins-builtins
![screen shot 2017-06-22 at 00 07 05](https://user-images.githubusercontent.com/601530/27394507-0170fa42-56df-11e7-9bd2-fab3238fb410.png)

**Comment by MasseGuillaume** [comment]
this was fixed somehow
