### ISSUE TITLE
use scopt or similar library for command line args parsing

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#428]
Entry points:

* https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/Server.scala#L23
* https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/Main.scala#L43

**Comment by adpi2** [comment]
Closing this issue because we are trying to go away from command line job (the `data` module) to replace them with scheduled jobs (see `SchedulerService` class).
