### ISSUE TITLE
Seems the index is off? Cannot find typelevel/cats

### ISSUE THREAD

**Issue by kailuowang** [scalacenter/scaladex#430]

**Comment by MasseGuillaume** [comment]
![cats](http://weknowmemes.com/wp-content/uploads/2013/04/have-you-seen-this-cat.jpg)

Let me see what I can do.

**Comment by MasseGuillaume** [comment]
I found the error. I upgraded the elasticsearch version and it cannot index documents with empty keys. The empty key in question is the documentation link. The key is the label for the link and it's empty.

I'm going to set the label field required in the ui and manually fix it.

**Comment by MasseGuillaume** [comment]
It's now working properly: https://index.scala-lang.org/typelevel/cats

**Comment by kailuowang** [comment]
thanks!
