### ISSUE TITLE
GeoTrellis shows only bintray custom build version; should be latest maven central version

### ISSUE THREAD

**Issue by lossyrob** [scalacenter/scaladex#434]
[GeoTrellis]() shows up on scaladex, but lists the latest version as a custom build that one of our developers pushes to a bintray. Is there a way to modify it so it shows only official releases on sonatype, the latest of which is currently `1.1.1`? I wouldn't want users getting confused.

**Comment by MasseGuillaume** [comment]
@lossyrob 

I can add an option to filter version to only show: 1.0.0, 1.0.0-RC1 and 1.0.0-M2. By default, there is an option to show the latest stable release (pick 1.0.0 over 1.1.0-M1).

This is the current version list:

```
1.2.0-astraea.9
1.1.1
1.1.0
1.1.0-RC6
1.1.0-RC5
1.1.0-RC4
1.1.0-RC3
1.1.0-RC2
1.1.0-RC1
1.1.0-astraea.8
1.1.0-astraea.7
1.1.0-astraea.6
1.1.0-astraea.5
1.1.0-astraea.4
1.1.0-astraea.3
1.0.0
1.0.0-RC3
1.0.0-hdfs-tuning-1
1.0.0-fb57dc4
// long list of  1.0.0-$gitthash
0.10.3
0.10.2
0.10.1
0.10.0
0.10.0-RC4
0.10.0-RC3
0.10.0-RC2
0.10.0-RC1
0.10.0-M2
0.10.0-M1
0.10.0-test
0.10.0-cb236ac
0.10.0-OWM-M0-J7
0.10.0-OWM-M0
0.9.2
0.9.1
0.9.0
0.9.0-RC5
0.9.0-RC4
0.9.0-RC3
0.9.0-RC2
0.9.0-RC1
0.8.2-RC2
0.8.2-RC1
0.8.1
0.8.1-RC3
0.8.1-RC2
0.8.1-RC1
```

It would show: 

```
1.1.1
1.1.0
1.1.0-RC6
1.1.0-RC5
1.1.0-RC4
1.1.0-RC3
1.1.0-RC2
1.1.0-RC1
1.0.0
1.0.0-RC3
0.10.3
0.10.2
0.10.1
0.10.0
0.10.0-RC4
0.10.0-RC3
0.10.0-RC2
0.10.0-RC1
0.10.0-M2
0.10.0-M1
0.9.2
0.9.1
0.9.0
0.9.0-RC5
0.9.0-RC4
0.9.0-RC3
0.9.0-RC2
0.9.0-RC1
0.8.2-RC2
0.8.2-RC1
0.8.1
0.8.1-RC3
0.8.1-RC2
0.8.1-RC1
```

1.1.1 would be selected

does that make sense?

**Comment by lossyrob** [comment]
Yes, that would be ideal. Thank uou!
