### ISSUE TITLE
Resetting Custom Scala Doc doesn't work

### ISSUE THREAD

**Issue by MichaelViveros** [scalacenter/scaladex#441]
**Problem:** If you go to the edit project page, set Custom Scaladoc Link to some url, click update, edit the project again, reset the Custom Scaladoc Link to nothing, click update, the UI still has the old link in the Documentation section. And if you go back to the edit project page, the old link shows up in Custom Scaladoc Link even though you just reset it to nothing.

I found this issue because I'm implementing something similar in #432 where I added a Beginner Issues Label field to the edit project page and setting it to a value and then resetting it doesn't get rid of the old value.

**Cause**: After clicking the Update button in the edit project page, the server gets the new fields and updates Elastic Search in [`DataRepository.scala`](https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/DataRepository.scala#L275) but when it serializes the `Project` object from `Scala` to `JSON`, it leaves out attributes that are `None`. So setting `customScalaDoc` to empty in the UI will set it to `None` in the `Project` object and this field will be missing from the serialized `JSON` object so nothing gets changed in Elastic Search.

**Fix**: Updating the serialization format to preserve empty values fixed the issue.

Changing `elastic/package.scala` from:
```Scala
implicit val formats = Serialization.formats(
    ShortTypeHints(
      List(
        classOf[Milestone],
        classOf[ReleaseCandidate],
        classOf[OtherPreRelease],
        classOf[BintrayResolver]
      ))) + artifactKindSerializer
```

to:
```Scala
implicit val formats = Serialization.formats(
    ShortTypeHints(
      List(
        classOf[Milestone],
        classOf[ReleaseCandidate],
        classOf[OtherPreRelease],
        classOf[BintrayResolver]
      ))).preservingEmptyValues + artifactKindSerializer
```

The only side effects I noticed were that project fields that were `None` and not stored in elastic search or [`projects.json`](https://github.com/scalacenter/scaladex-index/blob/master/live/projects.json) will be now.

@MasseGuillaume Does this fix make sense (no undesirable side effects)? If it does, I can submit a PR.

**Comment by MasseGuillaume** [comment]
@MichaelViveros thank for this detailed explanation. I think it would make sense to create a PR for this.

It can cause errors like https://github.com/scalacenter/scaladex/issues/430#issuecomment-311641444
