### ISSUE TITLE
Filters not working on front page

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#443]
Scala Native filter on front page is broken (#402 reports this). You have to then select Scala Native again on the next page.

**This is probably also the case for other links on the front page as well, I didn't test them all.**

**Comment by MasseGuillaume** [comment]
duplicates #402

**Comment by heathermiller** [comment]
Please check that other links aren't also broken. Thanks.

**Comment by MasseGuillaume** [comment]
https://github.com/scalacenter/scaladex/commit/8f4f5d6c000f336c41a48f27077f4fd609f79f79
