### ISSUE TITLE
Search bar on front page appears to do nothing for a few seconds

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#460]
Steps to reproduce:

1. Type something into the search bar on the front page.
2. Use the down arrow key to select the library you want.
3. Press enter.
4. Be confused about why nothing appears to happen for a few seconds.

It takes a few seconds for anything to happen. Every time I visit Scaladex recently, I first think that the JS on the front page is broken. After a second or two, I notice the browser status in the bottom left corner change from nothing to "Waiting for https://index.scala-lang.org..."

This seems to be a recent change in behavior; I don't remember Scaladex being this slow to respond to my input 2 months ago. 

In any case, it's confusing – I recall that @olafurpg thought the same thing a few weeks ago when we were all together in BC359.

**Comment by adpi2** [comment]
It is probably fixed because I cannot reproduce the issue.
