### ISSUE TITLE
missing release for wix/accord

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#462]
0.7 available since the 9th of July
https://repo1.maven.org/maven2/com/wix/accord-core_2.12/

not on scaladex yet

/cc @holograph

**Comment by holograph** [comment]
Thanks! Was just about to do that :-)

**Comment by holograph** [comment]
I released 0.7.1 and it's already on Central (also reported correctly by `shields.io`), no changes on the index as of yet.

**Comment by MasseGuillaume** [comment]
@holograph It's currently reindexing. I will check in a couple of hours if it fix the issue.

0.7.1 is in maven central indeed: http://search.maven.org/#artifactdetails%7Ccom.wix%7Caccord-core_2.12%7C0.7.1%7Cjar

**Comment by MasseGuillaume** [comment]
@holograph it's now available: https://index.scala-lang.org/wix/accord/accord-api/0.7.1?target=_2.12
