### ISSUE TITLE
Searching with filter selected doesn't narrow down results

### ISSUE THREAD

**Issue by MichaelViveros** [scalacenter/scaladex#473]
Ex. Select filter targetType=Js, enter "quill" into the search box, 1012 results, https://index.scala-lang.org/search?q=quill&targetTypes=Js
This is the same number of results as just selecting filter targetType=Js (and not entering anything into the search box), https://index.scala-lang.org/search?q=&targetTypes=Js

The search term does result in projects matching it being displayed first (top 2 results from first link above are for quill projects) but it might be confusing if you just enter "quill" into search box (no filters selected), https://index.scala-lang.org/search?q=quill, and there's 10 results, but if you first select a filter (targetType=Js) and then enter "quill" into search box, you get more than 10 results (doesn't make sense because it's a more specific search).

**Comment by MasseGuillaume** [comment]
:+1: indeed this is bogus. Thanks for reporting.

**Comment by adpi2** [comment]
Resolved by #597
