### ISSUE TITLE
PublishProccess Back Pressure

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#478]
PublishProcess is too slow under a big load.

It loads Poms, fetch GitHub info and index in elasticsearch.

We should write the pom to disk as soon as possible and schedule an update for github and elasticsearch in bulk.

**Comment by MasseGuillaume** [comment]
Thanks @rjsvaljean!

**Comment by leonardehrenfried** [comment]
Does this mean that auto-indexing has resumed again?

**Comment by MasseGuillaume** [comment]
@leonardehrenfried for maven central yes :)
