### ISSUE TITLE
Question, how often is scala dex updated? 

### ISSUE THREAD

**Issue by kailuowang** [scalacenter/scaladex#481]
I noticed that the projects that I have haven't been updated on scaladex for weeks. We are using the scaladex badge which thus indicates outdated release versions.

**Comment by MasseGuillaume** [comment]
I turned off indexing for this week because of this issue: https://github.com/scalacenter/scaladex/issues/478

I'm turning the indexing back on, sorry about that!

**Comment by kailuowang** [comment]
thanks!

**Comment by MasseGuillaume** [comment]
@kailuowang what is the specific repo that is out of date?

**Comment by kailuowang** [comment]
thanks for asking, the one I care the most is typelevel/cats.

**Comment by MasseGuillaume** [comment]
oh I see, 1.0.0-MF is not a valid semantic version. let me see what I can do.

**Comment by MasseGuillaume** [comment]
This would be a valid semantic version: `1.0.0-M1+final`

Since it's too late, I will see if I can add an exception for cats without breaking the ordering for other libraries.

**Comment by kailuowang** [comment]
yah! thanks so much!

**Comment by MasseGuillaume** [comment]
np, it might not update now on the readme because of GitHub image proxy: https://help.github.com/articles/about-anonymized-image-urls/
