### ISSUE TITLE
the group id for scalatest artifact is "org.pageobject.patch.org.scalatest"

### ISSUE THREAD

**Issue by gigiyy** [scalacenter/scaladex#488]
is it due to some configuration error? couldn't find it on other packages though.

URL: https://index.scala-lang.org/scalatest/scalatest/scalatest/3.0.3?target=_2.12

**Comment by MasseGuillaume** [comment]
Thanks for reporting.

This is due to: https://github.com/scalacenter/scaladex/issues/178
