### ISSUE TITLE
Edit Project

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#49]
After being logged in a user can edit his project info:

accessible fields:
* [Project](https://github.com/scalacenter/scaladex2/blob/de110e037079b5459c742d84bbe8616a9e161bc3/model/src/main/scala/ch.epfl.scala.index.model/Project.scala#L12-L24)
* [Artifact](https://github.com/scalacenter/scaladex2/blob/de110e037079b5459c742d84bbe8616a9e161bc3/model/src/main/scala/ch.epfl.scala.index.model/Artifact.scala#L11)
* default artifact #158
* #100 scaladoc link

UI
* [x] dropdown multiselect for keywords
* [x] input box for other infos
* [x] dropdown for artifact deprecation

Backend
* [x] keywords dropdown api
* [x] deprecation dropdown api
* [x] update api

**Comment by xeno-by** [comment]
As a project owner, can I hide the artifact or an entire project that's been deprecated from other users?

**Comment by MasseGuillaume** [comment]
@xeno-by Unpublish ? What could possibly [go wrong](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm) ?

Just kidding, it's a good idea to remove some noise.

**Comment by marcospereira** [comment]
@xeno-by and @MasseGuillaume or maybe some way to clearly state that the project was abandoned. Also it could be removed from search/filters while still published.

**Comment by MasseGuillaume** [comment]
@marcospereira a simple solution would be to edit the README if possible.

we also have deprecation in plan:
https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/Artifact.scala#L15
https://github.com/scalacenter/scaladex/blob/eb45faaa847f49d1c30f99a010ca8acf24e8361d/model/src/main/scala/ch.epfl.scala.index.model/Deprecation.scala

**Comment by MasseGuillaume** [comment]
@marcospereira @xeno-by 
solved https://github.com/scalacenter/scaladex/pull/212/commits/123f8f32d3330101d9b38753e51bf55e3a5daa4f

**Comment by xeno-by** [comment]
@MasseGuillaume Is the UI for this already live?

**Comment by heathermiller** [comment]
👏 🎉 🍻

**Comment by MasseGuillaume** [comment]
@xeno-by not yet ;-)

**Comment by MasseGuillaume** [comment]
@xeno-by now it is :)
