### ISSUE TITLE
Use Jenkins to build/deploy

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#5]
Build + deploy upon Github post-commit

**Comment by MasseGuillaume** [comment]
* `sbt server/universal:packageBin`
* creates `server/target/universal/server-0.1.2.zip`
* copy to alaska
* inside alaska
  * reindex (until we have #36)
    * `cd scaladex && git pull`
    * stop server
    * `rm -rf ~/.esdata/data/`
    * `sbt data/reStart elastic`
  * start server

**Comment by heathermiller** [comment]
This is incomplete and unacceptable. It means minutes of downtime on redeploys.

**Comment by marcospereira** [comment]
Why not Travis CI (or other public service) to handle builds and maybe deploys? Circle CI also comes to my mind.

**Comment by MasseGuillaume** [comment]
@marcospereira a bit late to the party: we need a lot of RAM :-)

**Comment by MasseGuillaume** [comment]
* [ ] split build script into two parts: build phase and redeploying phase (run by sudo)
