### ISSUE TITLE
optimize large projects

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#510]
scalatest takes 11s to load:

https://index.scala-lang.org/scalatest/scalatest

https://index.scala-lang.org/api/project?organization=scalatest&repository=scalatest&target=JVM&scalaVersion=2.12.4

**Comment by MasseGuillaume** [comment]
The api is here: https://github.com/scalacenter/scaladex/blob/aa5e09a05a2847d70f9787997ba439842c99046a/server/src/main/scala/ch.epfl.scala.index.server/routes/api/SearchApi.scala#L161-L215

The slow part:
https://github.com/scalacenter/scaladex/blob/aa5e09a05a2847d70f9787997ba439842c99046a/server/src/main/scala/ch.epfl.scala.index.server/DataRepository.scala#L397-L411

We need to fetch all releases because the logic in DefaultRelease is not easily indexable.

**Comment by adpi2** [comment]
I fixed this issue a few time ago: https://github.com/scalacenter/scaladex/pull/624
