### ISSUE TITLE
Please do not hijack the ‘/’ key

### ISSUE THREAD

**Issue by yurikhan** [scalacenter/scaladex#512]
In Firefox, the `/` key brings up the find bar (like `Ctrl+F` but an easier key). Scaladex overrides this key to focus the search input field. If the user was in the middle of reading a long package description and wanted to search from that point, he/she will be taken to the top of page, losing his/her reading position.

This is probably the relevant part of the code: [Client.scala#L143-L153](https://github.com/scalacenter/scaladex/blob/master/client/src/main/scala/ch.epfl.scala.index.client/Client.scala#L143-L153)

**Comment by MasseGuillaume** [comment]
:heart: sorry about that. Can you create a PR? I can deploy it right away.

**Comment by yurikhan** [comment]
Just like that? No prolonged arguments about “many of our users actually expect `/` to focus the search bar, and anyway `Ctrl+F` does the same thing as you yourself admit so what’s the problem”? :)

Regarding a PR, well, I *think* it involves deleting that method plus also the line that hooks it to `keydown` at [Client.scala#L294](https://github.com/scalacenter/scaladex/blob/master/client/src/main/scala/ch.epfl.scala.index.client/Client.scala#L294), but I’m a bit insecure about testing it. It’s literally my second day with Scala. Maybe you’d do the honors instead?

**Comment by MasseGuillaume** [comment]
> Just like that? No prolonged arguments about “many of our users actually expect / to focus the search bar, and anyway[,] Ctrl+F does the same thing as you yourself admit so what’s the problem”? :)

We could disable it only for Firefox for example.

> Regarding a PR, well, I think it involves deleting that method plus also the line that hooks it to keydown at Client.scala#L294, but I’m a bit insecure about testing it. It’s literally my second day with Scala. Maybe you’d do the honors instead?

This project is really contributor friendly, of course fixing the issue myself would be pretty quick, but I think it would be better if you could do the contribution yourself.

You will need sbt and java. Then you can follow our contribution guide:
https://github.com/scalacenter/scaladex/blob/master/CONTRIBUTING.md#how-to-run-scaladex-locally

**Comment by yurikhan** [comment]
> We could disable it only for Firefox for example.

Browser sniffing is considered a bad and error-prone thing, and Firefox is not the only browser with a quick find feature. Midori and Konqueror and GNOME Web have it, too, enabled by default. In Opera, it is under advanced key shortcuts.

Maybe we can agree on a different shortcut key.

**Comment by piotrkwiecinski** [comment]
Let me know which one would be preferred and I can create new PR.

**Comment by yurikhan** [comment]
@piotrkwiecinski I do not have a preference, only that it does not override any of the important browser keys. Presumably, you implemented the feature because you personally want it, so it’s up to you to choose something that is convenient for you.

I propose `s` because that’s what Github uses and I have not seen any other site that has an easy non-conflicting shortcut for its search input.

**Comment by piotrkwiecinski** [comment]
I've used ```/```, because it's used in other apps gmail, jira and even github in issues search (not repository/top one). I don't mind changing it to ```s```. I'll send PR within few minutes.

**Comment by yurikhan** [comment]
(Interestingly, I do not experience the problem with Github.)

**Comment by piotrkwiecinski** [comment]
I've just checked the Firefox and it just doesn't highlight search issues. Question is if it's a bug or feature :). Based on docs it should focus issue search bar and it does in Chrome.
