### ISSUE TITLE
Shapeless not showing up in api search

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#514]
https://index.scala-lang.org/api/search?q=shapeless&target=JVM&scalaVersion=2.12.4

**Comment by kailuowang** [comment]
neither are cats and scalaz

**Comment by halfninja** [comment]
Seems to be because it's marked as 2.13 only in [the results](https://index.scala-lang.org/search?q=shapeless) when it actually supports 2.10+

This is most annoying in Scastie where I can't add Shapeless as a library in a 2.12 worksheet. How has nobody else bumped into this?

**Comment by adpi2** [comment]
`scalaVersion=2.12.4` is not a valid `scalaVersion` anymore, it should be `2.12`. Apart from that the issue seems to be fixed:
https://index.scala-lang.org/api/search?q=shapeless&target=JVM&scalaVersion=2.12
