### ISSUE TITLE
README on GitHub project page shows a badge with an older version

### ISSUE THREAD

**Issue by plokhotnyuk** [scalacenter/scaladex#515]
I released v0.2 yesterday here:
https://github.com/plokhotnyuk/jsoniter-scala

If I try get image by following link directly: https://index.scala-lang.org/plokhotnyuk/jsoniter-scala/macros/latest.svg?color=blue then it displays latest version right by redirection to https://img.shields.io/badge/macros-0.2-blue.svg

But home page of the project on GitHub where README.md displays this badge rendering an image for the older version v0.1.

Is it caching or redirect handling problem on GitHub side or I should use https://img.shields.io/badge/macros-0.2-blue.svg in README.md directly?

**Comment by MasseGuillaume** [comment]
It looks like HTTP code 307 might be cached. I think the solution is to add [`cachingProhibited`](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/caching-directives/cachingProhibited.html) to the Bagde api https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/routes/Badges.scala#L57
