### ISSUE TITLE
Can't type the letter 's' in search bar

### ISSUE THREAD

**Issue by SeZuo** [scalacenter/scaladex#518]
Copy-paste works, but typing letter s does not.

Every other key seems to work.

Tried using Dvorak and US layout on ch and jp keyboard.

My s-key works by the way, and it's not the same key on the dvorak and us layout.

**Comment by MasseGuillaume** [comment]
Hum it looks like the culprit is https://github.com/scalacenter/scaladex/blob/master/client/src/main/scala/ch.epfl.scala.index.client/Client.scala#L149

if the searchbox is focused it should not prevent the default (typing s in the input box).

**Comment by wkomendera** [comment]
@MasseGuillaume, can I work on this ?

**Comment by MasseGuillaume** [comment]
@wkomendera all yours!

**Comment by MasseGuillaume** [comment]
fixed in https://github.com/scalacenter/scaladex/pull/520, thanks @wkomendera 

deployed
