### ISSUE TITLE
searching for utest shows me Scala 2.10 results

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scaladex#521]
if I search "utest" and then click on the top search result, I get taken to:

    https://index.scala-lang.org/lihaoyi/utest/utest-runner/0.2.4?target=_2.10

where's the `target=_2.10` coming from? this seems like a bug of some kind; utest is certainly available for newer Scala versions, and Scala 2.10 is very nearly dead these days so I wouldn't expect it to be the preferred version for Scaladex to show me.

/cc @lihaoyi

**Comment by MasseGuillaume** [comment]
I selected the default artifact: utest and it's poiting to the correct release now: https://index.scala-lang.org/lihaoyi/utest/utest/0.6.3?target=_2.12
