### ISSUE TITLE
broken image link on utest page

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scaladex#522]
at e.g. https://index.scala-lang.org/lihaoyi/utest/utest-runner/0.2.4?target=_2.10

there is a broken image link pointing to https://index.scala-lang.org/lihaoyi/utest/utest-runner/docs/Splash.png which is 404.

**Comment by MasseGuillaume** [comment]
This normally fix urls.
https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/github/GithubReadme.scala#L7

I have to investigate.

**Comment by SethTisue** [comment]
it seems this got fixed at some point
