### ISSUE TITLE
version badge shows old version

### ISSUE THREAD

**Issue by ktoso** [scalacenter/scaladex#536]
This shows 10.0.13 now: [![Latest version](https://index.scala-lang.org/akka/akka-http/akka-http-core/latest.svg)](https://index.scala-lang.org/akka/akka-http)

` [![Latest version](https://index.scala-lang.org/akka/akka-http/akka-http-core/latest.svg)](https://index.scala-lang.org/akka/akka-http)`

While if you were to click that, you correctly get the 10.1.1 https://index.scala-lang.org/akka/akka-http/akka-http-core/10.1.1?target=_2.12

How can we make sure the latest right version is used?

**Comment by 2m** [comment]
Does it still show the old version? It shows up fine here: http://i.imgur.com/nuem1Fr.png

I guess the old version is cached somewhere.

**Comment by MasseGuillaume** [comment]
If you are referring to: https://github.com/akka/akka-http,
GitHub use a proxy for image: https://help.github.com/articles/about-anonymized-image-urls/
This might explain the delay.

On our side, the caching should be correct: https://github.com/scalacenter/scaladex/pull/524

**Comment by ktoso** [comment]
Oh, I see -- that seems to be the case. 

Perhaps we should be using cache busters like ?t=21321323 in queries to the image then?

**Comment by ktoso** [comment]
I did a PURGE and it helped.
Thanks, closing here then I guess.

```
$ curl -X PURGE https://camo.githubusercontent.com/7b1522b66746b631fe6da21c99d7745a61d9d07b/68747470733a2f2f696e6465782e7363616c612d6c616e672e6f72672f616b6b612f616b6b612d687474702f616b6b612d687474702d636f72652f6c61746573742e737667
{"status": "ok", "id": "18724-1520617270-1013"}
```

Though the cache buster part still may be worth considering maybe
