### ISSUE TITLE
Scaladex does not index new version of "com.github.gvolpe" %% "fs2-rabbit"

### ISSUE THREAD

**Issue by gvolpe** [scalacenter/scaladex#538]
I reported it a while ago on #530 but since it was closed and this is not yet resolved, I'm raising this issue here:

The latest version of `fs2-rabbit` 0.5 has not been indexed by Scala Dex yet, though it's already on Maven Central since the 5th of April: http://search.maven.org/#search%7Cga%7C1%7Cfs2-rabbit

**Comment by adpi2** [comment]
It seems to be fixed: https://index.scala-lang.org/profunktor/fs2-rabbit/fs2-rabbit/0.8?target=_2.12
