### ISSUE TITLE
Latest version of akka/reactive-kafka does not show

### ISSUE THREAD

**Issue by ennru** [scalacenter/scaladex#539]
Reactive-kafka [was published on April, 6th](https://github.com/akka/reactive-kafka/releases) and is available from Maven central, but [Scaladex still lists 0.19 as the latest version](https://index.scala-lang.org/akka/reactive-kafka/akka-stream-kafka).

The Maven central badge correctly shows 0.20 as its current version.

**Comment by Atry** [comment]
Same bug for my library:
* Maven Central Badge: [![Maven Central](https://img.shields.io/maven-central/v/com.thoughtworks.dsl/dsl_2.13.svg)](https://search.maven.org/search?q=g:com.thoughtworks.dsl)
* Scaladex Badge: [![Latest version](https://index.scala-lang.org/ThoughtWorksInc/Dsl.scala/latest.svg)](https://index.scala-lang.org/ThoughtWorksInc/Dsl.scala)

**Comment by ennru** [comment]
Yes, it is still wrong even after the rename of "reactive kafka" to Alpakka Kafka: https://index.scala-lang.org/akka/alpakka-kafka/akka-stream-kafka

**Comment by julienrf** [comment]
I’ve re-indexed the projects and now the latest releases are correct for these projects. I’m closing this issue.

**Comment by ennru** [comment]
Thank you.
