### ISSUE TITLE
Feature Request: Try on scastie

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scaladex#540]
After finding a library on scaladex, it would be awesome if there were a tryout on scastie link that would launch a scastie session with the library loaded.

**Comment by heathermiller** [comment]
THIS WOULD BE AMAZING!!

**Comment by MasseGuillaume** [comment]
See it in action:
https://index.scala-lang.org/milessabin/shapeless/shapeless/2.3.3?target=_2.12

**Comment by ShaneDelmore** [comment]
That's pretty slick.  It initially confused me by adding shapeless to my previous worksheet instead of making a new one but that might be a nice behavior for adding multiple libs.
