### ISSUE TITLE
Add "mill" tab for quick ivy dependency copy/paste

### ISSUE THREAD

**Issue by Baccata** [scalacenter/scaladex#543]
Mill's syntax to set ivy dependencies in a project is very similar to Ammonite's, and the two are from the same author, so maybe they ought to be in the same tab. 

But here's ammonite syntax for magic imports : 

```scala 
import $ivy.`org.http4s::http4s-core:0.18.12`
```

Here's mill's for ivy dependencies : 

```scala
ivy"org.http4s::http4s-core:0.18.12"
```

**Comment by MasseGuillaume** [comment]
Hi @Baccata if you can create a pull request for this, it would be really appreciated. Here is the relevant code: 

https://github.com/scalacenter/scaladex/blob/892b67c214b04e57fc535ff534f6b337ac6bcffa/model/src/main/scala/ch.epfl.scala.index.model/Release.scala#L47-L131

https://github.com/scalacenter/scaladex/blob/892b67c214b04e57fc535ff534f6b337ac6bcffa/template/src/main/twirl/ch.epfl.scala.index.views/project/install.scala.html#L1-L45

**Comment by Baccata** [comment]
Cool, thanks for pointing me in to the right direction, I'll send PR as soon as I find the time

**Comment by rusucosmin** [comment]
PR #565 opened.
