### ISSUE TITLE
The RTree2D library that has been released a month ago is not indexed still

### ISSUE THREAD

**Issue by plokhotnyuk** [scalacenter/scaladex#545]
https://github.com/Sizmek/rtree2d/releases

It is available on JCenter repo: http://jcenter.bintray.com/com/sizmek/rtree2d/

**Comment by MasseGuillaume** [comment]
@heathermiller we need to rerun the Bintay indexing

**Comment by plokhotnyuk** [comment]
Please, also, ensure that JCenter indexing work properly, because it has some defense against crawlers. Please spot `:` character in the "href" attribute:
```
<a onclick="navi(event)" href=":core_2.12-0.1.0.jar.md5" rel="nofollow">core_2.12-0.1.0.jar.md5</a>
```

**Comment by MasseGuillaume** [comment]
@plokhotnyuk we use the rest api, we just need to run manually the Bintray indexing from time to time. If you publish to maven central, you get indexed in Scaladex right away.

**Comment by plokhotnyuk** [comment]
Ok, thanks! 

It would be great to automate Bintray scanning or clearly describe Maven Central and Bintray differences in Scaladex docs.

**Comment by MasseGuillaume** [comment]
https://github.com/scalacenter/scaladex#how-it-works

**Comment by plokhotnyuk** [comment]
In the readme it is stated: `Pull Bintray (once per day)`,  not `per month` or `manually by request`. 

But,  any way, thanks for the all the great work you done!

**Comment by mlachkar** [comment]
Hello!
We have reworked the index process, and normally all your artifacts are now available, this problem should not happen anymore hopefully! 
Thanks!
