### ISSUE TITLE
The "s" character doesn't work in artifact search

### ISSUE THREAD

**Issue by kubukoz** [scalacenter/scaladex#546]
Example: go to https://index.scala-lang.org/lloydmeta/enumeratum/enumeratum-circe/1.5.17?target=_2.12

Click "enumeratum-circe", start typing "enumeratum-slick" - you'll be moved to the main search bar and start searching.

Expected behavior: just input text into the artifact name search box.

Probably some change around https://github.com/scalacenter/scaladex/blob/master/client/src/main/scala/ch.epfl.scala.index.client/Client.scala#L144 is needed

**Comment by julienrf** [comment]
Indeed there is a global event listener that changes the focus when the `s` key is pressed.

A solution could be to use a combination of keys, for instance “Ctrl + S”?

**Comment by rusucosmin** [comment]
Opened #564 #

**Comment by julienrf** [comment]
Fixed by #564
