### ISSUE TITLE
Search results relevance

### ISSUE THREAD

**Issue by jendakol** [scalacenter/scaladex#551]
I think there is still place for better relevance detection for search results.
E.g. why https://index.scala-lang.org/search?q=http+client&targetTypes=Jvm&scalaVersions=2.12 gives `scala/scala` as the first (most relevant) result when it's definitely not an http client?

**Comment by MasseGuillaume** [comment]
Duplicate of https://github.com/scalacenter/scaladex/issues/389

**Comment by MasseGuillaume** [comment]
If you search for http-client: https://index.scala-lang.org/search?q=http-client&topics=http-client

Scaladex will propose you to use the topic http-client:  https://index.scala-lang.org/search?q=http-client&topics=http-client

**Comment by jendakol** [comment]
Well, ok... With the topic it's much better.
But it still doesn't explain the "http client" <-> "scala" relation.

**Comment by adpi2** [comment]
Search relevance has been improved since then, by #597.
@jendakol, you should give it a second try.
