### ISSUE TITLE
Scaladex doesn't pick up a new package

### ISSUE THREAD

**Issue by sideeffffect** [scalacenter/scaladex#552]
It seems like Scaladex isn't picking up the new [`scalaz-zio`](https://github.com/scalaz/scalaz-zio), available at both
 * https://oss.sonatype.org/content/repositories/releases/org/scalaz/scalaz-zio_2.12/
 * https://repo.maven.apache.org/maven2/org/scalaz/scalaz-zio_2.12/

could you please explain to us what we're doing wrong?

in case it's relevant, there's already this on Scaladex https://index.scala-lang.org/7mind/scalaz-zio/scalaz-zio-interop/0.1.0?target=_2.12
could that be causing some issues?

**Comment by MasseGuillaume** [comment]
I'm taking a look. I don't see anything out of the ordinary. 7mind is not the problem, I think we just did not receive the update from maven central.

**Comment by MasseGuillaume** [comment]
Hum, it ended up in the scalaz project for some reason: https://index.scala-lang.org/scalaz/scalaz/scalaz-zio.

**Comment by sideeffffect** [comment]
although I'm not 100% sure what's the meaning of the 3 level hierachy (I'm only familiar with 2 level hierarchies, as in GitHub for example), I believe that's wrong
it should be in `scalaz/scalaz-zio/whatever`
@jdegoes @NeQuissimus can you guys please confirm this?

**Comment by NeQuissimus** [comment]
Yeah, that's weird... If you look through that page now, it lists the meta info for scalaz/scalaz but points to the ZIO artifact.
Something is definitely wrong :)

Is there anything we can do on the project side to fix this?

**Comment by sideeffffect** [comment]
`scalaz-zio` got lumped up with other `scalaz` packages under `scalaz/scalaz`, which is obviously wrong.
it's a self-standing project, so it (`scalaz-zio` and `scalaz-zio-interop` to be precise) belongs to `scalaz/scalaz-zio`

@MasseGuillaume can you please help us out here? can you move it there yourself? or do you know who can?

**Comment by sideeffffect** [comment]
@MasseGuillaume ping :)

**Comment by sideeffffect** [comment]
[`https://index.scala-lang.org/scalaz/scalaz-zio`](https://index.scala-lang.org/scalaz/scalaz-zio) still doesn't show anything
thanks for fixing this @MasseGuillaume @julienrf :)

**Comment by sideeffffect** [comment]
@MasseGuillaume ping :)

**Comment by julienrf** [comment]
The zio artifact is correctly indexed: https://index.scala-lang.org/zio/zio/zio

**Comment by jdegoes** [comment]
@julienrf Thanks for the update and for looking into it! 🙏 🕺
