### ISSUE TITLE
Apache Daffodil (Incubating) not being found/incorporated into scaladex

### ISSUE THREAD

**Issue by mbeckerle** [scalacenter/scaladex#554]
Seems it should be finding this automatically as it is served from maven central. There are two releases already there 2.1.0, and now 2.2.0.

However, I am unable to determine from what's written here whether there is a manual step required to edit claims.json, or what that edit entails. 

The blog post that supposedly contains instructions on how to add a project is not very helpful. Begins with 

1. Login to GitHub in Scaladex
2. Go to your project’s page in Scaladex and click Edit

Ah... right there, I have no such page.... full stop.

**Comment by MasseGuillaume** [comment]
This is because the `<scm>` tag of your POM does not point to a GitHub repository:

https://search.maven.org/classic/#artifactdetails%7Corg.apache.daffodil%7Cdaffodil-core_2.12%7C2.2.0%7Cjar

```xml
   <scm>
        <url>https://gitbox.apache.org/repos/asf/incubator-daffodil.git</url>
        <connection>scm:git:https://gitbox.apache.org/repos/asf/incubator-daffodil.git</connection>
    </scm>
```

You can add a line to claims.json: 

https://github.com/scalacenter/scaladex-contrib/blob/master/claims.json

```
"org.apache.daffodil *": "apache/incubator-daffodil"
```

**Comment by mbeckerle** [comment]
Created PR for the claims.json line:

https://github.com/scalacenter/scaladex-contrib/pull/46

If someone would please merge it.

**Comment by mbeckerle** [comment]
It has been over a week, and Daffodil still does not show up on Scaladex.  Besides the claims.json change is there something else that has to change. 

We did not modify the pom.xml - I interpreted that as not necessary given the claims.json change. Am I incorrect here?

**Comment by MasseGuillaume** [comment]
@mbeckerle hum, I will rerun the index.

**Comment by mbeckerle** [comment]
So I detected that the site changed. Now says 6112 projects, yesterday it had 6111.

However, Daffodil is still not one of them.

**Comment by mbeckerle** [comment]
Hello? ApacheCon is next week, and I'd very much like to get Daffodil listed in the Scaladex before then.

**Comment by MasseGuillaume** [comment]
It's now indexed at: https://index.scala-lang.org/apache/incubator-daffodil It looks like 2.12 artifacts are missing, I'm taking a look

**Comment by mbeckerle** [comment]
Thanks. I see it is indexed. This is progress.

I am not visible as a contributor to this project once I am logged in, but it should recognize me as a contributor (I think) as I login to github with same ID for commits to this project.

I do not have any ability to edit. I'd like to add a link to our beginner-issues list, etc.

**Comment by MasseGuillaume** [comment]
@mbeckerle we get this information from GitHub api.

Can you validate you are a contributor with:

https://developer.github.com/v4/explorer/

```
query { 
  viewer { 
    repositories(first: 100) {
      nodes {
        nameWithOwner
      }
    }
  }
}
```

If you have a lot of private repository, we only fetch the first 100.

**Comment by mbeckerle** [comment]
Results of that query are:
```
{
  "data": {
    "viewer": {
      "repositories": {
        "nodes": [
          {
            "nameWithOwner": "mbeckerle/scala-unsigned"
          },
          {
            "nameWithOwner": "mbeckerle/xmlcalabash1"
          },
          {
            "nameWithOwner": "mbeckerle/mbeckerle-public-domain"
          },
          {
            "nameWithOwner": "mbeckerle/test1"
          },
          {
            "nameWithOwner": "mbeckerle/incubator-daffodil"
          },
          {
            "nameWithOwner": "mbeckerle/ontmalizer"
          },
          {
            "nameWithOwner": "mbeckerle/dfdlschemas.github.com"
          },
          {
            "nameWithOwner": "mbeckerle/incubator-daffodil-site"
          }
        ]
      }
    }
  }
}
```

**Comment by MasseGuillaume** [comment]
> I do not have any ability to edit. I'd like to add a link to our beginner-issues list, etc.

Issues are from Github label, since your issue tracker is on Jira it wont be picked up.

**Comment by adpi2** [comment]
It seems to be fixed. See https://index.scala-lang.org/apache/daffodil/daffodil-core/3.2.1?target=_2.12.
