### ISSUE TITLE
my multiple projects are not on scaladex

### ISSUE THREAD

**Issue by fluency03** [scalacenter/scaladex#563]
Here's GitHub repos:

- [fluency03/scala-multicodec](https://github.com/fluency03/scala-multicodec)
- [fluency03/scala-multibase](https://github.com/fluency03/scala-multibase)
- [fluency03/varint](https://github.com/fluency03/varint)

Here's Maven centrals:

- [Maven central - scala-multicodec](https://search.maven.org/search?q=g:%22com.github.fluency03%22%20AND%20a:%22scala-multicodec_2.12%22)
- [Maven central - scala-multibase](https://search.maven.org/search?q=g:%22com.github.fluency03%22%20AND%20a:%22scala-multibase_2.12%22)
- [Maven central - varint](https://search.maven.org/search?q=g:%22com.github.fluency03%22%20AND%20a:%22varint_2.12%22)

And I have already put the scmInfo in the build.sbt in each of my projects.

**Comment by Atry** [comment]
The same problem for https://github.com/ThoughtWorksInc/dsl-domains-cats:

[![Latest version](https://index.scala-lang.org/ThoughtWorksInc/dsl-domains-cats/latest.svg)](https://index.scala-lang.org/ThoughtWorksInc/dsl-domains-cats)
[![Maven Central](https://img.shields.io/maven-central/v/com.thoughtworks.dsl/domains-cats_2.12.svg)](https://search.maven.org/artifact/com.thoughtworks.dsl/domains-cats_2.12)

**Comment by mlachkar** [comment]
Hello! Your projects are now indexed ! https://index.scala-lang.org/fluency03/varint/varint/0.0.2?binaryVersion=_2.12
