### ISSUE TITLE
broken link on scala-parser-combinators page

### ISSUE THREAD

**Issue by sgdaw1041** [scalacenter/scaladex#569]
Hi,
Encountered a broken link on https://index.scala-lang.org/scala/scala-parser-combinators/scala-parser-combinators/1.1.1

The 'getting started link' on page is broken and returns a 404 error. The faulty url  on your page leads to: https://github.com/scala/scala-parser-combinators/blob/master/docs/Getting_Started.md 

After some rooting  around github, I found a "Getting Started" on github site at following url: https://github.com/scala/scala-parser-combinators/blob/1.1.x/docs/Getting_Started.md

**Comment by Philippus** [comment]
maybe this line: https://github.com/scalacenter/scaladex/blob/master/data/src/main/scala/ch.epfl.scala.index.data/github/GithubDownload.scala#L282
assumes that the default branch is always "master". It is possible to get the default branch through graphql:

```
query{
  repository(owner: "scala", name: "scala-parser-combinators") {
    defaultBranchRef {
      name
    }
  }
}
```
so it should be possible to fix this I think.

**Comment by adpi2** [comment]
Seems to be working now https://index.scala-lang.org/scala/scala-parser-combinators/scala-parser-combinators/1.1.1
