### ISSUE TITLE
try on scastie: library is not visible in scastie list

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/scaladex#570]
i've added the support for proper request here: https://github.com/scalacenter/scastie/compare/ec8e03763148...c4540d2e9f00

we just need to pass `o=<organization>&r=<repository>` to scastie in addition to other parameters to fix it

**Comment by adpi2** [comment]
Is this issue still relevant? If yes, please feel free to reopen it and to explain what the expected result should be.

**Comment by OlegYch** [comment]
the expected result is that going from scaladex to scastie via 'try on scastie' should add the library in library list like this:
![image](https://user-images.githubusercontent.com/268312/150140007-62313dc1-c82d-4b48-a8aa-0bf9928882df.png)

**Comment by OlegYch** [comment]
@adpi2 please reopen, i can't do it from my account

**Comment by OlegYch** [comment]
added some docs on 'try library' feature https://github.com/scalacenter/scastie/#try-library

**Comment by adpi2** [comment]
Superseded by #1019
