### ISSUE TITLE
"Topics" in GitHub seems not fully indexed

### ISSUE THREAD

**Issue by exoego** [scalacenter/scaladex#576]
Scaladex allow users to filter dependency by "Topics".
I assume these topics are collected from "Topics" metadata in GitHub .
![image](https://user-images.githubusercontent.com/127635/62430298-97e54900-b755-11e9-9038-7be7ab787ef6.png)

However, it seems that Scaladex index only some part of GitHub topics.
`topics=scalafix` for example, 
* https://index.scala-lang.org/search?topics=scalafix have only 2 dependencies
* https://github.com/topics/scalafix shows 10 repositories.

Ofcourse, the numbers may not match in case the repository do not publish artifacts, or in case single repository publishes many artifacts.
However, it is strange that the below repositories are tagged with `scalafix` topics in GitHub and have published artifacts, but not shown in Scaladex `topics=scalafix` query.

* https://github.com/NeQuissimus/sort-imports
* https://github.com/DmytroMitin/AUXify

**Comment by julienrf** [comment]
I guess this is because these projects are *not* indexed at all: https://index.scala-lang.org/DmytroMitin/AUXify

**Comment by adpi2** [comment]
This issue seems to be fixed
