### ISSUE TITLE
Wrong 'Website' link on Scaladex for gvolpe / fs2-redis

### ISSUE THREAD

**Issue by rubyfin** [scalacenter/scaladex#581]
Looks like the correct url should be https://redis4cats.profunktor.dev/.
See here: https://index.scala-lang.org/gvolpe/fs2-redis/fs2-redis-core/0.7.0?target=_2.12

**Comment by adpi2** [comment]
Fixed, see https://index.scala-lang.org/profunktor/redis4cats/redis4cats-core/1.0.0?target=_3
