### ISSUE TITLE
search results include duplicates

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scaladex#605]
for example, I searched "agent", and repos that were listed twice in the results included json4s/json4s and netlogo/netlogo:

<img width="297" alt="Screen Shot 2020-03-26 at 10 48 07 AM" src="https://user-images.githubusercontent.com/161079/77679237-81436a80-6f4f-11ea-94a0-034987e3fa71.png">

**Comment by adpi2** [comment]
Thank you @SethTisue . This bug is related to this old one #598 and so I close it.

**Comment by SethTisue** [comment]
ah, I had not noticed that the results depended on how fast I typed!
