### ISSUE TITLE
Search api is broken

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/scaladex#617]
`https://index.scala-lang.org/api/search?q=cats&target=JVM&scalaVersion=2.13.1`
returns 400 `something is wrong: None 2.13.1 None None None`

**Comment by OlegYch** [comment]
cc @adpi2

**Comment by adpi2** [comment]
@OlegYch thank you for reporting. I think the search api is still working fine.
However `2.13.1` does not look like a valid Scala binary version. There should be no `cats` library and no other library published for Scala `2.13.1`, they all should be published for Scala `2.13` instead.
You should try this request: `https://index.scala-lang.org/api/search?q=cats&target=JVM&scalaVersion=2.13`

**Comment by OlegYch** [comment]
it was working before...
just want to make sure that this change was intentional

**Comment by adpi2** [comment]
You are right. We intentionally changed the spec of the search API to make it easier to maintain.

**Comment by OlegYch** [comment]
what if i want to search for library published against full scala version? eg kind-projector

**Comment by sjrd** [comment]
That's then a compiler plugin, not really a library. We don't have a good solution for them at the moment. AFAIK kind-projector is the only compiler plugin that does not have an associated regular library. I thought there wasn't any, but you reminded me of kind-projector. I'm not sure what to do about that at the moment.

**Comment by OlegYch** [comment]
ok, thanks
