### ISSUE TITLE
dirty-money copy button gives obsolete version

### ISSUE THREAD

**Issue by LeeTibbert** [scalacenter/scaladex#620]
First, thank you for providing a place to find up-to-date information.

In the spirit of continuous improvement:

I tried using the `copy` button in the `Documentation` section on the far right of
the `dirty-money` page  to get the sbt text to cut & paste.  Neat feature! and useful.  

I believe the information that goes into the clipboard is obsolete.  It is at
the far right of the text box, so easy to miss.  The text to the left gives
the current version as `0.2.0`.  The text that goes to the clipboard is `0.1.0`.

When I use the pasted info, the artifact can not be resolved.  When I 
change it to `0.2.0`, life is good.

I think there is also some obsolete information in the three pulldown menues
immediately above the `Documentation` section.  I am using the text in
the `setup` section as my reference and only base of knowledge.

If this is something I can PR, please point me to the Contributor's Guide and
I will take a run at it.  

Otherwise, thank you for considering my information.

**Comment by LeeTibbert** [comment]
The ReadMe.md and CONTRIBUTING.md seem to give info for changing the bits
of scaladex itself; the tool not the data output.

The issue I described has to do with the content generated for
one item (and possibly others).   If I am reporting that data error in the wrong place,
please kindly re-direct me & sorry for the noise.

**Comment by adpi2** [comment]
Thank you @LeeTibbert for reporting this issue and offering your help.

The indexing of new artifacts in Scaladex is automated by either Scaladex pulling from Bintray or Maven pushing to Scaladex.

In this case, the release `0.2.0` of the artifact `sbt-dirty-money` has been published to Bintray in Feb 2018 but is still missing in Scaladex. So something has gone wrong when Scaladex tried to pull it from Bintray. I will first check the Scaladex database out, it is possible that the pom is present but that Scaladex refuses to index it for some reason.

**Comment by adpi2** [comment]
The `sbt-dirty-money`is publsihed to a Bintray repository called `sbt-plugin-releases` that is not automatically sync to Scaladex. So I will try to import the full repository to Scaladex in forthcoming days.

**Comment by LeeTibbert** [comment]
@adpi2  Thank you for your rapid & helpful action.   I have had my head down chasing some bugs 
and have been tardy expressing my appreciation.

Over my time of using Scaladex I have discovered few discrepancies. If I do discover such, how should I report them?  Same way as this one?    I saw nothing on the quite elegant web page
describing reporting errata. Sorry if I missed the Big Red Button.

From personal experience, I know how hard it is to keep a large database dependent on feeds
up-to-date.

**Comment by adpi2** [comment]
Hello @LeeTibbert,

I have submitted #622 for being able to import all the sbt-plugins that have been published to the [sbt/sbt-plugin-releases](https://bintray.com/sbt/sbt-plugin-releases) Bintray repository.

Unfortunately there is no Big Red Button. So I encourage you to report any discrepancies to the [Issues section](https://github.com/scalacenter/scaladex/issues) of this respository, as you did for this one. Also I would be grateful if you could submit some PR as well to help us, at the [Scala Center](https://scala.epfl.ch/), to maintain Scaladex.

**Comment by LeeTibbert** [comment]
@adpi2  Thank you for fixing the issue with dirty-money I reported.  I am late to the party but I can 
confirm that scaladex is now reporting the correct latest version.

I seldom encounter issues with scaladex but will continue to report them as I find them.  I appreciate
your description of the Issue reporting procedure & the invitation to contribute.  I am an active
contributor on another ScalaCenter project and have un-kept promises there but I will keep
Scaladex in mind.
