### ISSUE TITLE
Missing supported scala versions for some projects

### ISSUE THREAD

**Issue by plokhotnyuk** [scalacenter/scaladex#627]
As example, jsoniter-scala is released for Scala 2.11.x, 2.12.x from the first release but [the Scala Index have stopped showing that](https://index.scala-lang.org/search?q=jsoniter-scala):

![image](https://user-images.githubusercontent.com/890289/86528378-93666a80-bea7-11ea-8fce-6467dc4c1921.png)

**Comment by adpi2** [comment]
Thank you for reporting this.

The root cause is the same as #626. I'll see what I can do.

**Comment by adpi2** [comment]
The bug is fixed and Scaladex has been redeployed.
