### ISSUE TITLE
"Page doesn't redirect properly" on lihaoyi/upickle-pprint

### ISSUE THREAD

**Issue by antekone** [scalacenter/scaladex#630]
This URL:

https://index.scala-lang.org/lihaoyi/upickle-pprint

When entering, it will send a HTTP redirect header to `/lihaoyi/upickle`. After following this header, the HTTP server will send another HTTP redirect to `/lihaoyi/upickle-pprint`, entering an unlimited loop.

Firefox detects the redirect loop and breaks it, ending with "This page doesn't redirect properly" error, but it's impossible to enter the project's page on Scaladex. 

Some other projects I've entered (e.g. `jwt-scala`) work fine.

**Comment by adpi2** [comment]
Thank you for catching this error. I will have a look!

**Comment by adpi2** [comment]
Apparently the `upickle-pprint` repo was renamed `upickle`. There is yet to find why this is causing this error and how to fix it.

**Comment by adpi2** [comment]
There was two redirections in the `scaladex-index/github/moved.json` file:
```
"lihaoyi/upickle":"lihaoyi/upickle-pprint",
"lihaoyi/upickle-pprint":"lihaoyi/upickle",
```
I don't really know how this was inserted but it clearly caused a loop of redirection.

I removed the `"lihaoyi/upickle-pprint":"lihaoyi/upickle"` to fix it for now on.

If at some point it appears again, then it would mean there is something wrong with `lihaoyi/upickle` pom files.
