### ISSUE TITLE
3.0.0-M1 binary versions are not appearing

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#637]
In the project page, for instance https://index.scala-lang.org/typelevel/cats, the scala 3.0.0-M1 binary versions are not appearing:

For the cats project we would like to see the `3.0.0-M1` version of `cats-core` for instance.
https://repo1.maven.org/maven2/org/typelevel/cats-core_3.0.0-M1/

Is the artifact stored in the prod `scaladex-index` folder?
Is it indexed in elasticsearch?

**Comment by tgodzik** [comment]
@adpi2 I think we should be ok to close this too.
