### ISSUE TITLE
Artifact dependency list is broken

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#639]
The Scala dependencies are not shown correctly:

For example the https://index.scala-lang.org/typelevel/cats/cats-core/2.3.0-M1?target=_0.27 shows

![Screenshot_2020-11-10 typelevel cats(1)](https://user-images.githubusercontent.com/13123162/98676930-90e7b600-235c-11eb-8528-67cc7ac924f5.png)

**Comment by mlachkar** [comment]
it's fixed now!
