### ISSUE TITLE
not enough space in typelevel/cats header

### ISSUE THREAD

**Issue by bishabosha** [scalacenter/scaladex#645]
<img width="1071" alt="Screenshot 2020-11-16 at 18 28 10" src="https://user-images.githubusercontent.com/13436592/99286693-7ec4b680-2839-11eb-992a-98610c13708b.png">

when I made the version matrix button originally, I did not expect that there could be badges as well

**Comment by adpi2** [comment]
I've just reworked the project header UI.

You can see the result:
https://index.scala-lang.org/typelevel/cats/cats-core/2.3.0-M1?target=_0.27

**Comment by bishabosha** [comment]
awesome
