### ISSUE TITLE
sttp is not listed as scala3-compatible

### ISSUE THREAD

**Issue by adamw** [scalacenter/scaladex#646]
While it is :) https://github.com/softwaremill/sttp

sttp-model and sttp-shared are properly listed as compatible.

**Comment by adpi2** [comment]
Thanks for raising this and thank you for the effort you put in the Scala 3 migration.

As far as I can tell, `sttp` is not published on Scala `3.0.0-M1` or `3.0.0-M2`.

We  (the Scala Center) recently decided to exclude all the Dotty versions (of the form `0.x.y`) from the list of `scala3` projects in Scaladex to avoid some confusion. Also we encourage library maintainers to try the upcoming `3.0.0-M3` which will hopefully be the last release before RC1.

Sorry for the temporary inconvenience...

**Comment by adamw** [comment]
Ah makes sense. I totally forgot that I didn't deploy for 3.0.0-M1 as I was waiting for ZIO 🤦 sorry for that :) And thank you for the explanation
