### ISSUE TITLE
Some pages can't fetch README

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#65]
An example is here: https://index.scala-lang.org/lihaoyi/derive

Also, this page is repeating the right column again.

**Comment by MasseGuillaume** [comment]
duplicates #48

**Comment by heathermiller** [comment]
This is still an issue. See #128

**Comment by Scyks** [comment]
This is fixed actually, #128, #108, #134 are different things, and also already fixed (PR #136, #135).
@heathermiller can we close this then?

**Comment by heathermiller** [comment]
I didn't dig into this issue at all, I just noticed that in addition to the interpolation bug in #128, the README was not being fetched. Can you confirm that for the pages I mentioned in #128 that the README is now being fetched given #136?

**Comment by Scyks** [comment]
Yes i can confirm that with #136 the Problem of #128 is gone. I tested locally and cleand up https://github.com/scalacenter/scaladex-poms See: https://github.com/scalacenter/scaladex-poms/pull/2

**Comment by heathermiller** [comment]
Just to be clear, there are two issues in #128 that I can see. One is the interpolation issue, the other is the README not being fetched. READMES are being displayed for the pages andyglow/websocket-scala-client and ensime/ensime?

**Comment by heathermiller** [comment]
(PS I saw scalacenter/scaladex-poms#2 earlier today. Well done! Fastest bugfix ever.)

**Comment by Scyks** [comment]
I'll check locally

**Comment by heathermiller** [comment]
Woot, thanks :) Despite all the fixes to this issue, it seems to keep popping up again from time to time... :/

**Comment by Scyks** [comment]
As i mentioned here: https://github.com/scalacenter/scaladex/pull/135#discussion_r69376665 the process need to be optimized. There are coming issues from several sides. Some of them are related to the claims fix and some to the interpolation problem.

**Comment by heathermiller** [comment]
I see. So, let's leave this open until all the PRs are merged? If this appears to be gone in a few days, we close.

**Comment by Scyks** [comment]
Actually, this one (https://index.scala-lang.org/lihaoyi/derive) is fixed already live. I'm currently checking #128 locally and write a report to #128

**Comment by heathermiller** [comment]
So the interpolation fix should fix the rest!

**Comment by Scyks** [comment]
in combination with  #134
