### ISSUE TITLE
Shapeless 2.X is missing

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#71]
/cc @milessabin

**Comment by milessabin** [comment]
Any ideas?

**Comment by MasseGuillaume** [comment]
https://github.com/scalacenter/scaladex/blob/2dd56473a2392e196d22f9c529457c1c1e018363/data/src/main/scala/ch.epfl.scala.index.data/maven/PomsReader.scala#L98

You publish osgi bundle. My mistake.

**Comment by MasseGuillaume** [comment]
@milessabin https://index.scala-lang.org/milessabin/shapeless
latest version 2.3.1
