### ISSUE TITLE
Add documentation links to projects

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#84]
For example https://github.com/tpolecat/doobie#documentation-and-support

/cc @tpolecat

**Comment by Fristi** [comment]
Links would be awesome. However having one site which has the documentation it self would be awesome. Good examples are Hackage and Pursuit (Purescript). Bonus points if we could add searching for functions as well by specifying types for example (ala Hoogle). But doc blocks and function names are a good source of what a library is about as well.

**Comment by MasseGuillaume** [comment]
[Pursuit Example](https://pursuit.purescript.org/packages/purescript-aff-coroutines/2.0.0/docs/Control.Coroutine.Aff)
[Hackage](https://hackage.haskell.org/package/pokitdok-4.1.0.2/docs/PokitDok-Client.html)

**Comment by MasseGuillaume** [comment]
@Fristi 
![demo](https://cloud.githubusercontent.com/assets/921490/17087634/ee2a9a5e-51dc-11e6-8816-a150e17262fe.gif)

**Comment by tpolecat** [comment]
👍

**Comment by Fristi** [comment]
I like! 👍
