### ISSUE TITLE
Invalid scala version passed to scastie

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/scaladex#864]
eg clicking 'try on scastie' here https://index.scala-lang.org/sksamuel/elastic4s/elastic4s-core/7.16.2?target=_2.13 goes to `https://scastie.scala-lang.org/try?g=com.sksamuel.elastic4s&a=elastic4s-core&v=7.16.2&t=JVM&sv=Some(2.13)`

**Comment by adpi2** [comment]
Thanks for the clarification!

**Comment by OlegYch** [comment]
we need to pass organization and repository as well for library to be correctly displayed https://github.com/scalacenter/scaladex/issues/570

**Comment by adpi2** [comment]
Superseded by #1019
