### ISSUE TITLE
Schedule job to find missing artifacts from Maven Central

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#866]
## Motivation

Newly published artifacts on Maven Central are automatically pushed to Scaladex by Sonatype. However it is frequent that we miss some artifacts:
- There is a bug
- The Scaladex server is down
- Some new binary version is not yet supported

To handle these cases we used to launch the `CentralMissing` job manually. However it was not convenient for different reasons.  

A more useful thing would be to have a new `Scheduler` in the `SchedulerService` that runs a job every once in a while to find missing artifacts and download them.

### 1. Entrypoint in Maven Central

We may not be able to scan all maven central to find all the Scala libraries. But we can list all the artifacts of the organization (Maven `groupid`) that we know.

### 2. Java vs Scala artifacts

Java artifacts should not be indexed, except a few exceptions that is listed statically somewhere.

### 3. Rate limit

The Sonatype API has some rate limit mechanism. We should make sure that we use the permitted rate but that we don't hit the limit.

## Implementation guidelines

1. Create a `SonatypeClient` that can call the Sonatype API to find and download artifacts from Maven Central. 
2. Create a new scheduler that uses the `SchedulerDatabase` and the `SonatypeClient` to find missing artifacts.
3. Configure this new scheduler to run every once in a while (every week).

## Expectations

1. The `SonatypClient` should be tested (in `IntegrationTest`)
2. The `SonatypeClient` should be protected against rate limit errors
3. The `CentralMissing` code should be removed

**Comment by SethTisue** [comment]
I noticed just now that Scaladex still lists the latest version of zinc as being 1.6.0, even though 1.6.1 was released 28 days ago.

Should I open a ticket on that specifically, or does this ticket indicate that it's actually expected for Scaladex to be a month behind...?

**Comment by adpi2** [comment]
Thanks for reporting. We had a problem with publication between https://github.com/scalacenter/scaladex/pull/776 and https://github.com/scalacenter/scaladex/pull/817 and that's why some artifacts are missing. It is now fixed but we still have a one month hole in our database. The purpose of this issue is to fill this kind of hole.

So no need to create a new ticket.
