### ISSUE TITLE
Filter for scala.js binaries

### ISSUE THREAD

**Issue by Fristi** [scalacenter/scaladex#90]
You can determine if a specific version of a lib has scala.js artifact, by checking the convention of it's output files.

Would be awesome to have a filter for such a thing

**Comment by MasseGuillaume** [comment]
This is possible right now:
https://index.scala-lang.org/scala-js/scalajs-library/0.6.9

Look under dependent there is 139 !

I had an idea where you could have a url for this
/search?dependents=scala-js:scalajs-library:0.6.9

**Comment by Fristi** [comment]
I see! Great stuff. The endpoint would be nice as well 👍 

Making it more apparent that a lib is scala.js compatible is something nice to have. It also promotes to have a scala.js compatible version of your lib.
