### ISSUE TITLE
Dependency block

### ISSUE THREAD

**Issue by Fristi** [scalacenter/scaladex#91]
Currently all dependencies are listed on the right side as one block for each dependency. While this already a great thing, wouldn't it be great to have a list of all artifacts for one project in one place.? Put checkboxes in front of each dependency and a copy button to have a sequence of dependencies in your pasteboard?

**Comment by MasseGuillaume** [comment]
That's an excellant idea! I can change the artifact and the version selector to a multiselect dropdown.

**Comment by heathermiller** [comment]
Is this resolved?

**Comment by MasseGuillaume** [comment]
ops closed by mistake

**Comment by Fristi** [comment]
Think this is done
