### ISSUE TITLE
Get percentage of Scala code in a project from Github API

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#928]
## Motivation

In Scaladex we index all projects from which a Scala artifact was published. But currently we don't know if Scala is the primary language of the project or not.

Comparing the number of stars of Scala projects with projects from other ecosystems is not really fair because the latters can have bigger communities. Indeed in the top 20 projects in https://index.scala-lang.org/search?q=* only 8 of them uses Scala as their primary language.

To mitigate this we could get the percentage of Scala in each project using the Github API  and use it in the Elasticsearch scoring method. 

## Identified Obstacle

How to use the `scalaPercentage` in the scoring method?

## Implementation Guideline

- [x] Add a `scalaPercentage` field in `GithubInfo`
- [x] Get the information from Github in the `GithubClient`
- [ ] Add the `scalaPercentage` field in `GithubInfoDocument` that is indexed in elasticsearch
- [ ] Use this field in the  `githubStarScoring` method of `ElasticsearchEngine`

## Expectations

- A majority of the top 20 projects in https://index.scala-lang.org/search?q=* should use Scala as their primary language.
- the `GithubClient` should be tested

**Comment by jyoo980** [comment]
Would it be okay if I took this on?

**Comment by adpi2** [comment]
@jyoo980 Thanks for volunteering on this issue, it is really cool! I assigned it to you.

Let me know if you need some more information or some help.

**Comment by jyoo980** [comment]
@adpi2 I think the task

>  Add the scalaPercentage field in GithubInfoDocument that is indexed in elasticsearch

Is also complete. I'd be happy to also include the `scalaPercentage` field in the scoring function, but I think that's something that needs deeper discussion  🙂

**Comment by adpi2** [comment]
Scaladex is powered by a database, Postgres, and by a search engine, Elasticsearch. Those are two different things.

In #933 you added `scalaPercentage` in the `github_info` table of the Postgres database. Now we need to add it to the elasticsearch index too so that we can use it in the scoring function of the search.

To do so you can add the field `scalaPercentage` in [`GithubInfoDocument`](https://github.com/scalacenter/scaladex/blob/main/modules/core/shared/src/main/scala/scaladex/core/model/search/GithubInfoDocument.scala) and then declare it in the `projectFields` of [`ElasticsearchMapping`](https://github.com/scalacenter/scaladex/blob/71e652b18e6af3c47ad1cd98f11f4e09a90028ca/modules/infra/src/main/scala/scaladex/infra/elasticsearch/ElasticsearchMapping.scala#L45).

 For the scoring in `ElasticsearchEngine`, I suggest we try something like this:

```scala
val scorer = scriptScore(
  Script("Math.log(doc['githubInfo.stars'].value * doc['githubInfo.scalaPercentage'].value")
)
functionScoreQuery()
  .query(query)
  .functions(scorer)
  .boostMode(CombineFunction.Multiply)
```

But probably the script should be adapted to deal with `null` values.

Have you been able to start the server locally?

**Comment by jyoo980** [comment]
> Have you been able to start the server locally?

I have the Docker environment running, but I think I'm running into issues with ARM compatibility. This is the error I run into when I run `server/run`

```sh
[IJ]server/run
[info] Trying to connect to elasticsearch on port 64477
[info] Elasticsearch has already started on port 64477
[info] Postgres has already started on port 64481
[info] Full optimizing /Users/yoo/workspace/scaladex/modules/webclient/target/scala-2.13/webclient-opt
[info] Sass compiling on 1 source(s)
[info] Closure: 0 error(s), 0 warning(s)
[error] stack trace is suppressed; run last server / Web-assets / sassify for the full output
[error] (server / Web-assets / sassify) java.lang.UnsatisfiedLinkError: dlopen(/Users/yoo/Library/Caches/JNA/temp/jna13032095721934704484.tmp, 0x0009): tried: '/Users/yoo/Library/Caches/JNA/temp/jna13032095721934704484.tmp' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/jna13032095721934704484.tmp' (no such file)
[error] Total time: 8 s, completed Mar. 5, 2022, 11:51:38 a.m.
```

**Comment by adpi2** [comment]
> I have the Docker environment running, but I think I'm running into issues with ARM compatibility. This is the error I run into when I run server/run

Docker seems to work fine. However our current version of sbt-sassify is not compatible with ARM (it is based on the native `libsassify` library). But the PR https://github.com/scalacenter/scaladex/pull/935 should fix it.

Could you pull main and try to run the server again?

**Comment by jyoo980** [comment]
Hey! Sorry for the delayed response; busy times working on my thesis.

I generally take the weekend to be more active on my open-source activities, so I'll take a look this Saturday/Sunday!

**Comment by adpi2** [comment]
no problem

**Comment by jyoo980** [comment]
Changes ready in #934
