### ISSUE TITLE
Reverse the order of the badges

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#932]
I think that JVM should be first then Js 1.x, Js 1.6, Native... This can be achieve with `.sortBy(_.platform)(Platform.ordering.reverse)`.

![image](https://user-images.githubusercontent.com/13123162/156394289-798769e4-a937-490b-bc0e-7a4aa6eeda1a.png)

**Comment by mlachkar** [comment]
it's not the version deployed currently on preprod
