### ISSUE TITLE
fix or don't replicate github readme

### ISSUE THREAD

**Issue by cvogt** [scalacenter/scaladex#94]
I see that scaladex shows a project's readme from github. There are bugs / usability degradations though in comparison. It's not being syntax highlighted. And the width is smaller, so some code samples are cut off. Do links to other files work?

So one way to go would be fixing all these bugs and replicating (and maintaining) readme display.

On the other hand users already get that nicely on github and github even maintains it. So another way to look at it would be: why waste effort on getting this right and maintaining it. Scala index could just focus on displaying all the links to important places instead, readme being one of them.

**Comment by nafg** [comment]
Also some refs are broken, like img src pointing to camo2.githubusercontent.com (see gitter).

But displaying the readme is helpful. 

(FWIW @MasseGuillaume indicated on gitter that that the md->html is being done by github)

**Comment by cvogt** [comment]
@nafg is it more helpful displaying a potentially broken readme than linking to a working one? Not sure, but want to put the idea on the table :).

**Comment by nafg** [comment]
Well, it's still readable...

I would say it's definitely more helpful. If it was a commercial product I would ask, is it harming our reputation, but I think the community understands that it's a WIP.

**Comment by MasseGuillaume** [comment]
> It's not being syntax highlighted.
It is

> And the width is smaller, so some code samples are cut off.
github: 888px
scaladex: 690px
I can make this a bit larger so it's == to github

> Do links to other files work
They do

> On the other hand users already get that nicely on github and github even maintains it. 
There is a lot of information in the readme (build status, gitter.im, etc). This is why we inline it in the page. 
I prefer to fix the width issue and #93.
