### ISSUE TITLE
Data viz library

### ISSUE THREAD

**Issue by Quafadas** [scalacenter/scaladex#944]
I've been trying to incubate an idea for a data viz library. Written in scala 3, 

https://quafadas.github.io/dedav4s/

https://github.com/Quafadas/dedav4s

I guess it would be great to have it included here, if I can.

**Comment by julienrf** [comment]
Hello, it is automatically included, see here: https://index.scala-lang.org/quafadas/dedav4s :relaxed:

**Comment by Quafadas** [comment]
Oh cool. Thanks.
