### ISSUE TITLE
doesn't work well with moved/renamed projects

### ISSUE THREAD

**Issue by cvogt** [scalacenter/scaladex#95]
This project: https://github.com/xdotai/play-json-extensions
moved from https://github.com/cvogt/play-json-extensions

Now 

https://index.scala-lang.org/xdotai/play-json-extensions doesn't show old versions
https://index.scala-lang.org/cvogt/play-json-extensions does not show a forwarder to the new location.

Probably not the highest priority thing, but these things do happen, so maybe you guys can add it to the roadmap at some point.

**Comment by MasseGuillaume** [comment]
When I will solve #48, I will get the old -> new mapping.

**Comment by MasseGuillaume** [comment]
see #200

**Comment by MasseGuillaume** [comment]
I did it for you https://github.com/scalacenter/scaladex-data/commit/4d239aff9da326fd0c7993e08155245801dccb88

**Comment by MasseGuillaume** [comment]
There is a lot of repos that moved

from index.scala-lang.org/search?q=*&sort=stars
page 1 to 13 I can find

```json
{
  "org.squeryl *": "squeryl/squeryl",
  "org.monifu *": "monixio/monix",
  "com.newzly phantom*": "outworkers/phantom",
  "com.github.mpilquist scodec": "scodec/scodec",
  "com.adrianhurt play-bootstrap*": "adrianhurt/play-bootstrap",
  "org.reactivemongo *": "reactivemongo/play-reactivemongo",
  "io.argonaut *": "argonaut-io/argonaut",
  "tv.cntt xitrum*": "xitrum-framework/xitrum",
  "com.github.olegilyenko sangria": "sangria-graphql/sangria",
  "com.microsoft.sparkclr *": "microsoft/mobius",
  "ai.h2o sparkling-water-*": "h2oai/sparkling-water",
  "com.github.cb372 cacheable-*": "cb372/scalacache",
  "org.rogach scallop": "scallop/scallop",
  "edu.arizona.sista *": "clulab/processors",
  "com.github.seratch scalikejdbc-async-*": "scalikejdbc/scalikejdbc-async"
}
```

I think it would make more sense to dynamically ajust this. We can get this information when we scrape Github data. Also it would make more sense to keep the old repo but remove it from search results.

**Comment by vossad01** [comment]
>  Also it would make more sense to keep the old repo but remove it from search results.

I'm not entirely sure I understand that that would look like.  What would be accessible on the "old repo" page version page as opposed to the new?

I'm not sure it bears too much consideration, but I did think through the implication of this if Scaladex were to support other SCM providers.  The current routing scheme appears to not support moving from one SCM provider (ex. GitHub) to another (ex. BitBucket) and keeping the "old repo" active if the same organization and project names were used in both scm systems.

**Comment by MasseGuillaume** [comment]
It won't give you a 404 if you have the old url. Maybe redirect you to the new org/repo page.

**Comment by MasseGuillaume** [comment]
The workaround is to use claim.json to override the repo

For example:
> created a project, tabulate
> after a few releases, decided to rename it to kantan.csv for various reasons
> published a few releases of kantan.csv
> scaladex is created!
> can't remember whether I claimed either tabulate or kantan.csv

nrinaudo/tabulate moved to nrinaudo/kantan.csv

solution:

add `"com.nrinaudo tabulate_*": "nrinaudo/kantan.csv"` to [claims.json](https://github.com/scalacenter/scaladex-contrib/blob/master/claims.json)

**Comment by darkfrog26** [comment]
Is this being worked on?  I'm experiencing problems with a project that I renamed nearly a month ago and it still shows as the original name.

**Comment by MasseGuillaume** [comment]
@darkfrog26 I finally have some time to work on this. It should be fixed this week.

**Comment by darkfrog26** [comment]
@MasseGuillaume awesome...thanks for the update.

**Comment by MasseGuillaume** [comment]
Fixed locally. I'm redeploying tomorrow.

**Comment by MasseGuillaume** [comment]
@cvogt 

The history is now merged:

https://index.scala-lang.org/search?q=play-json-extensions

Shows only the new project

https://index.scala-lang.org/xdotai/play-json-extensions/play-json-extensions/0.7.0?target=_2.11

The project merge the older artifacts

https://index.scala-lang.org/cvogt/play-json-extensions

the url /org/repo/ is redirected to the new repo
