### ISSUE TITLE
Typos on Scaladex Page

### ISSUE THREAD

**Issue by rohantheman** [scalacenter/scaladex#961]
See attached for typos on page heading and navigation bar. The word "Mathematics" is misspelled 
<img width="1552" alt="Screen Shot 2022-03-21 at 17 39 18" src="https://user-images.githubusercontent.com/518428/159368428-4f6627a7-578f-4df2-afe1-d32b3f008346.png">

**Comment by adpi2** [comment]
Thanks for reporting it. Good catch!
